from __future__ import annotations

from collections.abc import Iterable, Mapping

from math_learning_graph.depth import (
    default_layers,
    default_practice_ladder,
    default_reflection_questions,
    default_worked_examples,
)
from math_learning_graph.models import (
    GradeBand,
    KnowledgePoint,
    PracticeTask,
    TextbookPosition,
    WorkedExample,
)

CURRICULUM = "人教版义务教育数学"


def _position(grade: str, chapter: str, section: str) -> TextbookPosition:
    return TextbookPosition(
        curriculum=CURRICULUM,
        grade=grade,
        chapter=chapter,
        section=section,
    )


def _point(
    *,
    topic_id: str,
    name: str,
    grade_band: GradeBand,
    grade: str,
    chapter: str,
    section: str,
    human: str,
    why: str,
    terms: Mapping[str, str],
    prerequisites: Iterable[str] = (),
    next_topics: Iterable[str] = (),
    formulas: Iterable[str] = (),
    examples: Iterable[str] = (),
    route: Iterable[str] = (),
    misconceptions: Iterable[str] = (),
    visuals: Iterable[str] = (),
    exercise_types: Iterable[str] = (),
    conceptual_layers: Iterable[str] = (),
    worked_examples: Iterable[WorkedExample] = (),
    practice_ladder: Iterable[PracticeTask] = (),
    reflection_questions: Iterable[str] = (),
) -> KnowledgePoint:
    route_items = list(route)
    point = KnowledgePoint(
        id=topic_id,
        name=name,
        grade_band=grade_band,
        textbook_positions=[_position(grade, chapter, section)],
        human_explanation=human,
        life_examples=list(examples),
        why_needed=why,
        formal_definition=human,
        term_explanations=dict(terms),
        misconceptions=list(misconceptions),
        prerequisite_ids=list(prerequisites),
        next_ids=list(next_topics),
        formulas=list(formulas),
        visualization_methods=list(visuals),
        ai_teaching_hints=[
            "不要默认学生懂关键词；先解释词，再解释关系。",
            "先问学生能不能用自己的话复述这个概念。",
        ],
        exercise_types=list(exercise_types),
        school_route=[grade, chapter, section],
        understanding_route=route_items or [name, "用人话解释", "图形或生活例子", "符号表达"],
    )
    return point.model_copy(
        update={
            "conceptual_layers": list(conceptual_layers) or default_layers(point),
            "worked_examples": list(worked_examples) or default_worked_examples(point),
            "practice_ladder": list(practice_ladder) or default_practice_ladder(name),
            "reflection_questions": list(reflection_questions)
            or default_reflection_questions(name),
        },
    )


def load_curriculum_knowledge_points() -> list[KnowledgePoint]:
    return [
        _point(
            topic_id="number_recognition",
            name="数的认识",
            grade_band=GradeBand.PRIMARY,
            grade="一年级上册",
            chapter="准备课与位置",
            section="数一数",
            human="数是用来回答“有多少”的工具。",
            why="后面所有计算、测量和比较都要先知道数在表示什么。",
            terms={"数": "表示多少的记号。", "计数": "一个一个对应着数出来。"},
            next_topics=["place_value_decimal_system", "integer_addition_subtraction"],
            examples=["数铅笔", "数台阶"],
            route=["一个物体对应一个数", "数的顺序", "多少", "数字记号"],
            visuals=["实物计数", "点子图"],
            conceptual_layers=[
                "数不是一个字，是「有多少」的回答："
                "3 支铅笔、3 级台阶、3 次拍手，说的是同一个「3」。",
                "数数的关键是一一对应：一个东西配一个数，不跳过也不重复，最后念到的数就是总数。",
                "数有顺序：往后数一个就多 1，往前数一个就少 1，所以数还可以用来比大小。",
            ],
            worked_examples=[
                WorkedExample(
                    title="数台阶：最后念到的数就是总数",
                    problem="上楼时边走边数：1、2、3、4、5、6、7。这段楼梯一共有几级台阶？",
                    steps=[
                        "一脚踩一级，嘴里念一个数：踩一级念 1，再踩一级念 2……",
                        "不跳级、不重复念，这叫一一对应。",
                        "最后一级念到 7。7 不只是最后一级的编号，它同时表示总共有 7 级。",
                    ],
                    answer_check="把 7 个东西打乱顺序重新数一遍，总数还是 7，说明你数对了。",
                ),
            ],
            practice_ladder=[
                PracticeTask(
                    level="看懂",
                    prompt="数一数家里任意一堆东西（碗、书、遥控器），说说为什么最后念到的数就是总数。",
                    goal="建立一一对应和「最后一个数=总数」的感觉。",
                ),
                PracticeTask(
                    level="会做",
                    prompt="数 12 颗豆子，数到一半停下再接着数。总数会变吗？为什么？",
                    goal="体会总数不随数的过程改变。",
                ),
                PracticeTask(
                    level="迁移",
                    prompt="不一个一个数：先把 10 个圈成一堆，再看剩几个，快速说出总数。",
                    goal="为「十个一捆」的位值思想做铺垫。",
                ),
            ],
            reflection_questions=[
                "3 支铅笔和 3 级台阶，「3」说的是同一件事吗？",
                "数数时跳过一个或重复一个，会出什么错？",
                "为什么最后念到的那个数刚好就是总数？",
            ],
        ),
        _point(
            topic_id="place_value_decimal_system",
            name="十进制与位值",
            grade_band=GradeBand.PRIMARY,
            grade="一年级下册至四年级上册",
            chapter="100以内数的认识 / 大数的认识",
            section="数位与计数单位",
            human="同一个数字放在不同位置，表示的大小不一样。",
            why="多位数、小数、竖式计算都靠位值来保证不乱。",
            terms={"数位": "数字所在的位置。", "计数单位": "一、十、百、千这样的单位。"},
            prerequisites=["number_recognition"],
            next_topics=["decimal", "integer_addition_subtraction"],
            examples=["23里的2表示2个十", "305里的0表示十位没有"],
            route=["一捆十个", "十个十是一百", "位置不同", "值不同"],
            visuals=["数位表", "小棒捆扎"],
            conceptual_layers=[
                "位值的核心约定只有一句话：满十个，就捆成一个更大的单位，往左挪一位。",
                "同一个数字「2」，在 23 里是 2 个十，在 32 里是 2 个一——位置在替你记住单位。",
                "有了这个约定，只用 0～9 十个数字就能写出任何大的数，这是数学里最省事的发明之一。",
            ],
            worked_examples=[
                WorkedExample(
                    title="为什么十要写成「10」",
                    problem="只有 0 到 9 这十个数字，数到十的时候该怎么写？",
                    steps=[
                        "数到 9 再多 1 个，个位已经放不下第十个「一」。",
                        "约定：把十个一捆成一个「十」，放到左边一位；个位空了，写 0 占住位置。",
                        "所以「10」的意思是：1 个十、0 个一——不是数字 1 和 0 恰好排在一起。",
                    ],
                    answer_check="能说出 10 里的 1 和 0 各表示什么，而不是背「一零就是十」。",
                ),
                WorkedExample(
                    title="23 和 32 为什么不一样大",
                    problem="同样用数字 2 和 3，为什么 23 和 32 差这么多？",
                    steps=[
                        "23：2 在十位，表示 2 个十；3 在个位，表示 3 个一，合起来是 20+3。",
                        "32：3 在十位，表示 3 个十；2 在个位，合起来是 30+2。",
                        "数字相同、位置不同，单位就不同——这就是「位值」两个字的意思。",
                    ],
                    answer_check="用小棒摆出 23 和 32（几捆带几根），一眼看出谁大、大在哪。",
                ),
            ],
            practice_ladder=[
                PracticeTask(
                    level="看懂",
                    prompt="把 47 说成「几个十和几个一」，再用小棒或画图摆出来。",
                    goal="把每个数字和它的计数单位对上。",
                ),
                PracticeTask(
                    level="会做",
                    prompt="在数位表里写出 208，说说每个数字各表示多少、0 在干什么。",
                    goal="读写多位数时不乱位。",
                ),
                PracticeTask(
                    level="迁移",
                    prompt="钟表上 60 秒进 1 分。它和「满十进一」像在哪里、不像在哪里？",
                    goal="体会进位制是一种约定，十进制只是最常用的一种。",
                ),
            ],
            reflection_questions=[
                "为什么是满十进一，而不是满八、满十二？（提示：看看你的手指）",
                "同一个数字换到另一个数位上，什么变了，什么没变？",
                "如果没有位值，要写「一千零一」得画多少个记号？",
            ],
        ),
        _point(
            topic_id="integer_addition_subtraction",
            name="整数加减法",
            grade_band=GradeBand.PRIMARY,
            grade="一年级上册至三年级上册",
            chapter="加法和减法",
            section="进位、退位与竖式",
            human="加法是在合起来，减法是在拿走或比较差多少。",
            why="这是理解数量变化和后续四则混合运算的入口。",
            terms={"进位": "某一位满十后换成高一位的一个。", "退位": "从高一位拆一个十来用。"},
            prerequisites=["place_value_decimal_system"],
            next_topics=["arithmetic_operations", "mixed_operations"],
            examples=["一共有多少本书", "还剩多少个苹果"],
            route=["合并或拿走", "按位对齐", "满十进一", "不够退一"],
            visuals=["数轴", "计数器"],
            conceptual_layers=[
                "加减法先是动作：合起来、拿走、比差距。算式只是把动作记下来。",
                "竖式的全部道理是一句话：相同单位才能直接相加减，所以数位要对齐。",
                "进位和退位不是新规则，就是位值反着用：满十捆走送上位，不够就从上位拆一个下来。",
            ],
            worked_examples=[
                WorkedExample(
                    title="37+25：满十为什么要进一",
                    problem="计算 37 + 25。",
                    steps=[
                        "个位：7+5=12。12 里藏着 1 个十和 2 个一。",
                        "2 留在个位；那个十不属于个位，捆起来送到十位——这就是「进 1」。",
                        "十位：3 个十加 2 个十，再加送来的 1 个十，共 6 个十。",
                        "所以 37+25=62。",
                    ],
                    answer_check="用 62-25 倒回去，能回到 37，说明进位的十没有丢。",
                ),
                WorkedExample(
                    title="52-38：退位「借」的到底是什么",
                    problem="计算 52 - 38。",
                    steps=[
                        "个位 2 减 8 不够减。",
                        "从十位拆 1 个十下来：52 变成 4 个十和 12 个一。数没变，只是换了摆法。",
                        "个位：12-8=4。十位：4-3=1。",
                        "所以 52-38=14。",
                    ],
                    answer_check="14+38 应该正好回到 52；加回去对不上，就是退位时把数弄丢了。",
                ),
            ],
            practice_ladder=[
                PracticeTask(
                    level="看懂",
                    prompt="用小棒或画图，把 37+25 里「进一」的那个动作演一遍。",
                    goal="亲眼看见进位捆走的是什么。",
                ),
                PracticeTask(
                    level="会做",
                    prompt="算 63-27，边算边说出每一位正在做什么。",
                    goal="退位靠理解，不靠背口诀。",
                ),
                PracticeTask(
                    level="迁移",
                    prompt="带 50 元买 32 元的书，还剩多少？"
                    "列式，并说出这是「拿走」还是「比差距」。",
                    goal="把算式接回生活里的数量动作。",
                ),
            ],
            reflection_questions=[
                "为什么个位的数不能直接和十位的数相加？",
                "进位写的那个小「1」，和个位上的「1」一样大吗？",
                "减法算完之后，怎么自己检查对不对？",
            ],
        ),
        _point(
            topic_id="multiplication_meaning",
            name="乘法的意义",
            grade_band=GradeBand.PRIMARY,
            grade="二年级上册",
            chapter="表内乘法",
            section="乘法的初步认识",
            human="乘法是在说几个相同的组一共有多少。",
            why="面积、比例、函数里的倍数关系都从乘法意义长出来。",
            terms={"几个几": "有几组，每组有同样多个。", "因数": "参与相乘的数。"},
            prerequisites=["integer_addition_subtraction"],
            next_topics=["division_meaning", "arithmetic_operations"],
            formulas=["a x b"],
            examples=["3盒彩笔，每盒6支", "4排座位，每排8个"],
            route=["重复加法", "相同组", "几个几", "乘法式子"],
            visuals=["阵列图", "分组图"],
            conceptual_layers=[
                "乘法不是新运算，是「同一个数加很多遍」的省事写法：每盒 6 支、3 盒，就是 6+6+6。",
                "用乘法的前提是「相同的组」：每组一样多才能乘；组不一样多，就先别乘。",
                "把组摆成一行一行，就是阵列："
                "横着看是 3 个 6，竖着看是 6 个 3——所以交换因数，总数不变。",
            ],
            worked_examples=[
                WorkedExample(
                    title="3 盒彩笔一共几支",
                    problem="每盒彩笔 6 支，3 盒一共多少支？",
                    steps=[
                        "先确认是「相同的组」：每盒都是 6 支，共 3 组。",
                        "用加法写：6+6+6=18。",
                        "加的都是同一个 6，改写成乘法：6×3=18，读作 3 个 6。",
                        "摆成 3 行 6 列的点阵，横着数、竖着数都是 18——因数交换，总数不变。",
                    ],
                    answer_check="能指着式子说出 6、3、18 各对应生活里的什么。",
                ),
            ],
            practice_ladder=[
                PracticeTask(
                    level="看懂",
                    prompt="找一个生活里「几个几」的例子（如 4 排椅子每排 8 把），"
                    "用加法和乘法各写一遍。",
                    goal="体会乘法是相同加数的简写。",
                ),
                PracticeTask(
                    level="会做",
                    prompt="画阵列图，说明 5×3 和 3×5 为什么一样多。",
                    goal="交换律有画面，不是背出来的。",
                ),
                PracticeTask(
                    level="迁移",
                    prompt="3 盒彩笔分别是 6 支、6 支、5 支，还能直接用 6×3 算总数吗？为什么？",
                    goal="识别「每组一样多」这个乘法前提。",
                ),
            ],
            reflection_questions=[
                "乘法帮我们省了什么事？",
                "什么时候不能直接用乘法算总数？",
                "看到 4×7，你脑子里出现的是什么画面？",
            ],
        ),
        _point(
            topic_id="division_meaning",
            name="除法的意义",
            grade_band=GradeBand.PRIMARY,
            grade="二年级下册",
            chapter="表内除法",
            section="平均分",
            human="除法是在平均分，或者看一个数量里有几个同样的组。",
            why="分数、比、比例和概率都需要理解平均分和每份多少。",
            terms={"平均分": "每份一样多。", "商": "除法算出的结果。"},
            prerequisites=["multiplication_meaning"],
            next_topics=["fraction", "arithmetic_operations"],
            formulas=["a ÷ b"],
            examples=["12颗糖平均分给4人", "18里面有几个3"],
            route=["平均分", "每份多少", "有几个组", "除法式子"],
            visuals=["分物图", "线段图"],
            conceptual_layers=[
                "除法有两张脸：平均分（12 颗糖分给 4 人，每人几颗）和包含（12 里面有几个 3）。",
                "除法和乘法是一对：12÷4=3，靠的是 4×3=12。会乘法口诀，就会算除法。",
                "分不完剩下的叫余数。余数一定比除数小——不然还够再分一轮。",
            ],
            worked_examples=[
                WorkedExample(
                    title="12 颗糖的两种分法",
                    problem="12 颗糖：(1) 平均分给 4 个人，每人几颗？(2) 每 3 颗装一袋，能装几袋？",
                    steps=[
                        "第 (1) 问是「平均分」：一人一颗轮着发，发完每人 3 颗，记作 12÷4=3。",
                        "第 (2) 问是「包含」：数 12 里面有几个 3，能装 4 袋，记作 12÷3=4。",
                        "两问都用除法，但一个在求「每份多少」，一个在求「有几份」。",
                        "都能用乘法验证：4×3=12，正好分完。",
                    ],
                    answer_check="拿到除法应用题，先说出它问的是「每份多少」还是「有几份」。",
                ),
            ],
            practice_ladder=[
                PracticeTask(
                    level="看懂",
                    prompt="用 18 个小物件，把 18÷6 的两种问法各演示一遍。",
                    goal="两种除法画面都亲手摆过。",
                ),
                PracticeTask(
                    level="会做",
                    prompt="算 14÷4，说清商和余数各是什么，余数为什么不能是 4。",
                    goal="理解「余数小于除数」的道理。",
                ),
                PracticeTask(
                    level="迁移",
                    prompt="全班 27 人春游，每辆车坐 6 人，需要几辆车？答案能是 4.5 吗？",
                    goal="余数在真实问题里要「进一」处理。",
                ),
            ],
            reflection_questions=[
                "12÷4 和 12÷3 问的问题有什么不同？",
                "为什么算除法可以靠乘法口诀？",
                "如果余数等于除数了，说明什么？",
            ],
        ),
        _point(
            topic_id="mixed_operations",
            name="四则混合运算",
            grade_band=GradeBand.PRIMARY,
            grade="三年级下册至四年级下册",
            chapter="四则运算",
            section="运算顺序",
            human="混合运算是在一个式子里安排多个数量动作的先后顺序。",
            why="应用题列综合算式、解方程和代数式变形都要守住运算顺序。",
            terms={"括号": "提醒里面先看作一个整体。", "运算顺序": "先算什么、后算什么的规则。"},
            prerequisites=[
                "integer_addition_subtraction",
                "multiplication_meaning",
                "division_meaning",
            ],
            next_topics=["distributive_property", "algebraic_expression"],
            examples=["先买几盒再加散装", "总价减优惠再平均分"],
            route=["一个动作", "多个动作", "先乘除后加减", "括号优先"],
            visuals=["步骤树", "数量动作图"],
        ),
        _point(
            topic_id="decimal",
            name="小数",
            grade_band=GradeBand.PRIMARY,
            grade="三年级下册至四年级下册",
            chapter="小数的初步认识 / 小数的意义和性质",
            section="小数表示与大小比较",
            human="小数是把1继续平均分成十分、百分、千分后写出来的数。",
            why="测量、钱数、百分数和函数图像都经常使用小数。",
            terms={"小数点": "整数部分和小数部分的分界。", "十分之一": "把1平均分成10份中的1份。"},
            prerequisites=["place_value_decimal_system", "division_meaning"],
            next_topics=["decimal_operations", "percent"],
            examples=["1.5米", "3.25元"],
            route=["单位1", "继续平均分", "十分位", "百分位", "小数点"],
            visuals=["数轴", "方格纸"],
        ),
        _point(
            topic_id="decimal_operations",
            name="小数运算",
            grade_band=GradeBand.PRIMARY,
            grade="五年级上册",
            chapter="小数乘法与小数除法",
            section="小数四则计算",
            human="小数运算还是数量动作，只是单位被分得更细。",
            why="实际测量和初中函数里的数值计算经常要用小数。",
            terms={"小数位": "小数点右边的位置。", "近似数": "接近准确值、方便使用的数。"},
            prerequisites=["decimal", "arithmetic_operations"],
            next_topics=["ratio", "linear_function"],
            examples=["每千克2.5元买3.2千克", "速度和时间相乘求路程"],
            route=["看单位", "按整数方法想", "处理小数点", "估算检验"],
            visuals=["面积模型", "数轴"],
        ),
        _point(
            topic_id="fraction_operations",
            name="分数运算",
            grade_band=GradeBand.PRIMARY,
            grade="五年级下册至六年级上册",
            chapter="分数的意义和性质 / 分数乘法与除法",
            section="通分、约分与分数四则运算",
            human="分数运算是在同一个单位1下处理几份、几倍和平均分。",
            why="比例、概率、代数分式都需要学生真正懂分数运算。",
            terms={
                "通分": "把分母变成相同，方便比较或加减。",
                "约分": "把分子分母同时缩小但大小不变。",
            },
            prerequisites=["fraction", "division_meaning"],
            next_topics=["ratio", "probability"],
            formulas=["a/b + c/d", "a/b x c/d"],
            examples=["半杯水再加四分之一杯", "一段路的三分之二"],
            route=["单位1", "同分母", "通分", "约分", "乘除意义"],
            visuals=["面积模型", "数轴"],
        ),
        _point(
            topic_id="percent",
            name="百分数",
            grade_band=GradeBand.PRIMARY,
            grade="六年级上册",
            chapter="百分数",
            section="百分数的意义和应用",
            human="百分数是把比较的标准统一成100份。",
            why="折扣、增长率、统计图和概率表达都会用百分数。",
            terms={"百分号": "表示以100为标准。", "增长率": "增加的部分占原来的百分之几。"},
            prerequisites=["fraction", "decimal"],
            next_topics=["probability", "data_analysis"],
            formulas=["a% = a/100"],
            examples=["打八折", "正确率95%"],
            route=["单位1", "100份", "占几份", "百分号", "实际问题"],
            visuals=["百格图", "条形图"],
        ),
        _point(
            topic_id="ratio",
            name="比",
            grade_band=GradeBand.PRIMARY,
            grade="六年级上册",
            chapter="比",
            section="比的意义",
            human="比是在比较两个数量之间的倍数关系。",
            why="比例、相似、三角函数和函数斜率都离不开比。",
            terms={
                "前项": "比号前面的量。",
                "后项": "比号后面的量。",
                "比值": "两个量相除得到的数。",
            },
            prerequisites=["fraction", "division_meaning"],
            next_topics=["proportion", "similar_triangles"],
            formulas=["a:b = a ÷ b"],
            examples=["果汁和水的配比", "地图比例尺"],
            route=["两个量", "谁和谁比", "除法", "比值", "等价的比"],
            visuals=["线段图", "双数轴"],
        ),
        _point(
            topic_id="proportion",
            name="比例",
            grade_band=GradeBand.PRIMARY,
            grade="六年级下册",
            chapter="比例",
            section="正比例、反比例和比例尺",
            human="比例是在说两个比相等，或者两个量按稳定规则一起变。",
            why="一次函数、反比例函数、相似图形和建模都需要比例直觉。",
            terms={
                "正比例": "一个量变成几倍，另一个量也变成几倍。",
                "反比例": "一个量变大，另一个量按乘积不变的方式变小。",
            },
            prerequisites=["ratio", "quantity_relationship"],
            next_topics=["linear_function", "inverse_proportion_function"],
            formulas=["a:b = c:d", "y = kx", "xy = k"],
            examples=["速度一定时路程和时间", "总量一定时每份和份数"],
            route=["比", "两个比相等", "变化关系", "正比例", "反比例"],
            visuals=["表格", "双数轴", "关系图"],
        ),
        _point(
            topic_id="negative_number_intro",
            name="负数初步",
            grade_band=GradeBand.PRIMARY,
            grade="六年级下册",
            chapter="负数",
            section="正负数表示相反意义的量",
            human="负数用来表示和正方向相反的量。",
            why="初中有理数、坐标系、不等式都要用负数。",
            terms={"正方向": "事先规定为正的方向。", "相反意义": "比如高于和低于、收入和支出。"},
            prerequisites=["number_recognition"],
            next_topics=["rational_numbers", "coordinate_plane"],
            examples=["零上和零下", "收入和支出"],
            route=["相反意义", "0作分界", "正数", "负数", "数轴"],
            visuals=["温度计", "数轴"],
        ),
        _point(
            topic_id="primary_equation",
            name="简易方程",
            grade_band=GradeBand.PRIMARY,
            grade="五年级上册",
            chapter="简易方程",
            section="用字母表示数与解简易方程",
            human="简易方程是把不知道的数先用字母占位，再用等量关系找出来。",
            why="这是从算术走向代数的关键桥梁。",
            terms={"字母": "暂时代替一个数的符号。", "解方程": "找出让等式成立的未知数。"},
            prerequisites=["equality", "quantity_relationship", "mixed_operations"],
            next_topics=["linear_equation_one_variable"],
            examples=["已知总价求数量", "已知周长求边长"],
            route=["不知道的数", "用字母表示", "等量关系", "方程", "求解"],
            visuals=["天平模型", "线段图"],
        ),
        _point(
            topic_id="measurement_units",
            name="常见量与单位",
            grade_band=GradeBand.PRIMARY,
            grade="二年级上册至三年级上册",
            chapter="长度单位 / 时、分、秒 / 质量单位",
            section="单位认识与换算",
            human="单位是在说明这个数到底数的是什么。",
            why="没有单位，测量、面积、速度和应用题都会失去意义。",
            terms={"单位": "约定好的测量标准。", "换算": "用不同单位表示同一个量。"},
            prerequisites=["number_recognition", "place_value_decimal_system"],
            next_topics=["perimeter", "area", "volume"],
            examples=["3米和3厘米不是一回事", "1小时等于60分钟"],
            route=["量什么", "选单位", "读数", "换算", "检验是否合理"],
            visuals=["尺子", "钟表", "天平"],
        ),
        _point(
            topic_id="line_angle_basic",
            name="线与角",
            grade_band=GradeBand.PRIMARY,
            grade="二年级下册至四年级上册",
            chapter="角的初步认识 / 角的度量",
            section="线段、直线、射线和角",
            human="线描述位置和方向，角描述两条线张开的大小。",
            why="平面图形、三角形、平行线和圆都需要线与角的语言。",
            terms={"线段": "有两个端点的一段直线。", "角": "从同一点出发的两条射线形成的图形。"},
            prerequisites=["measurement_units"],
            next_topics=["triangle_basic", "parallel_lines"],
            examples=["门打开的角度", "道路的交叉"],
            route=["点", "线段", "射线", "直线", "角", "度量"],
            visuals=["量角器", "折纸"],
        ),
        _point(
            topic_id="perimeter",
            name="周长",
            grade_band=GradeBand.PRIMARY,
            grade="三年级上册",
            chapter="长方形和正方形",
            section="周长",
            human="周长是一圈边线的总长度。",
            why="它帮助学生区分边界长度和内部面积。",
            terms={"边界": "图形最外面的一圈。", "总长度": "把每一段边长加起来。"},
            prerequisites=["measurement_units", "line_angle_basic"],
            next_topics=["area"],
            formulas=["长方形周长 = 2 x (长 + 宽)"],
            examples=["给操场围栏杆", "给画框包边"],
            route=["沿边走一圈", "每段边", "加起来", "公式只是简写"],
            visuals=["绕绳模型", "方格纸"],
        ),
        _point(
            topic_id="area",
            name="面积",
            grade_band=GradeBand.PRIMARY,
            grade="三年级下册至五年级上册",
            chapter="面积 / 多边形的面积",
            section="长方形、平行四边形、三角形和梯形面积",
            human="面积是在问一个平面图形里面铺了多少个单位小方格。",
            why="面积模型能解释乘法、分配律、几何公式和二次函数直觉。",
            terms={"面积单位": "用来铺满平面的单位小方格。", "底和高": "互相垂直的一组测量线。"},
            prerequisites=["perimeter", "multiplication_meaning"],
            next_topics=["volume", "distributive_property"],
            formulas=["长方形面积 = 长 x 宽", "三角形面积 = 底 x 高 ÷ 2"],
            examples=["铺地砖", "计算土地大小"],
            route=["铺方格", "数方格", "长乘宽", "割补转化", "公式"],
            visuals=["方格纸", "割补图"],
        ),
        _point(
            topic_id="volume",
            name="体积",
            grade_band=GradeBand.PRIMARY,
            grade="五年级下册",
            chapter="长方体和正方体",
            section="体积和容积",
            human="体积是在问一个立体里面能装多少个单位小正方体。",
            why="空间想象、单位换算和初中几何都需要体积直觉。",
            terms={"体积单位": "用来填满空间的小正方体。", "容积": "容器里面能装多少。"},
            prerequisites=["area", "measurement_units"],
            next_topics=["geometric_figures_intro"],
            formulas=["长方体体积 = 长 x 宽 x 高"],
            examples=["盒子能装多少", "水箱容量"],
            route=["一层方格", "很多层", "长宽高", "单位小正方体", "体积公式"],
            visuals=["积木模型", "展开图"],
        ),
        _point(
            topic_id="data_collection_chart",
            name="数据收集与统计图",
            grade_band=GradeBand.PRIMARY,
            grade="一年级下册至六年级上册",
            chapter="统计",
            section="分类、记录、条形统计图和扇形统计图",
            human="统计图是把一堆数据整理成容易看出多少和变化的图。",
            why="初中统计、概率和现实判断都要先会看数据。",
            terms={"数据": "记录下来的数量或信息。", "统计图": "用图形显示数据。"},
            prerequisites=["number_recognition", "percent"],
            next_topics=["data_collection_description", "data_analysis"],
            examples=["统计喜欢的运动", "看各类支出占比"],
            route=["收集", "分类", "记录", "画图", "读结论"],
            visuals=["条形图", "折线图", "扇形图"],
        ),
        _point(
            topic_id="average",
            name="平均数",
            grade_band=GradeBand.PRIMARY,
            grade="四年级下册",
            chapter="平均数与条形统计图",
            section="平均数",
            human="平均数是把总量重新分得一样多后每份是多少。",
            why="平均数是理解数据整体水平的第一种工具。",
            terms={"总量": "全部合起来的量。", "平均": "重新分成一样多。"},
            prerequisites=["division_meaning", "data_collection_chart"],
            next_topics=["data_analysis"],
            formulas=["平均数 = 总数 ÷ 份数"],
            examples=["平均身高", "平均每天读书页数"],
            route=["合起来", "重新平均分", "每份一样多", "代表整体水平"],
            visuals=["移多补少", "条形图"],
        ),
        _point(
            topic_id="rational_numbers",
            name="有理数",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第一章 有理数",
            section="有理数及其运算",
            human="有理数把正数、0、负数、分数和小数放进同一个数的系统。",
            why="初中代数从有理数开始扩展数的范围。",
            terms={
                "正数": "比0大的数。",
                "负数": "比0小、表示相反意义的数。",
                "数轴": "用线上的点表示数。",
            },
            prerequisites=["negative_number_intro", "fraction", "decimal"],
            next_topics=["absolute_value", "real_numbers", "algebraic_expression"],
            examples=["海拔低于海平面", "收入和支出"],
            route=["相反意义", "0", "数轴", "正负数", "有理数运算"],
            visuals=["数轴", "温度计"],
        ),
        _point(
            topic_id="absolute_value",
            name="绝对值",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第一章 有理数",
            section="数轴、相反数和绝对值",
            human="绝对值是在问一个数离0有多远，不管方向。",
            why="比较大小、解不等式和距离问题都需要绝对值。",
            terms={"距离": "两个位置之间隔了多远。", "相反数": "离0一样远但方向相反的两个数。"},
            prerequisites=["rational_numbers"],
            next_topics=["inequalities"],
            formulas=["|a|"],
            examples=["-3和3离0都是3格"],
            route=["数轴", "方向", "距离", "离0多远", "绝对值符号"],
            visuals=["数轴"],
        ),
        _point(
            topic_id="power_scientific_notation",
            name="乘方与科学记数法",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第一章 有理数",
            section="有理数的乘方",
            human="乘方是同一个数连续相乘的简写。",
            why="大数、小数、面积体积增长和二次函数都用到乘方。",
            terms={"底数": "被重复相乘的数。", "指数": "重复相乘的次数。"},
            prerequisites=["multiplication_meaning", "rational_numbers"],
            next_topics=["quadratic_equation", "quadratic_function"],
            formulas=["a^n", "a x 10^n"],
            examples=["10的6次方表示一百万", "正方形面积用边长的平方"],
            route=["重复乘", "简写", "底数", "指数", "科学记数法"],
            visuals=["方格面积", "数量级尺"],
        ),
        _point(
            topic_id="algebraic_expression",
            name="整式",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第二章 整式的加减",
            section="整式",
            human="整式是用数、字母和加减乘方拼出的数量表达。",
            why="方程、函数和公式都需要先会读懂式子。",
            terms={"单项式": "没有加减分开的一个整式块。", "多项式": "几个单项式加减组成的式子。"},
            prerequisites=["primary_equation", "mixed_operations"],
            next_topics=["like_terms", "polynomial_multiplication"],
            examples=["3x表示3个x", "2a+5表示某个量再加5"],
            route=["具体数", "字母代替数", "项", "整式", "式子含义"],
            visuals=["式子结构树", "面积模型"],
        ),
        _point(
            topic_id="like_terms",
            name="合并同类项",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第二章 整式的加减",
            section="整式的加减",
            human="同类项是同一种字母部分的数量，可以像同类物品一样合并。",
            why="解方程、化简函数表达式和因式分解前都要会合并。",
            terms={"项": "式子里被加减号分开的块。", "系数": "字母前面乘着的数。"},
            prerequisites=["algebraic_expression", "distributive_property"],
            next_topics=["linear_equation_one_variable"],
            examples=["3个苹果加2个苹果是5个苹果，3x+2x=5x"],
            route=["项", "字母部分相同", "系数相加", "字母部分不变"],
            visuals=["物品分类", "颜色标注式子"],
        ),
        _point(
            topic_id="geometric_figures_intro",
            name="几何图形初步",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第四章 几何图形初步",
            section="立体图形、平面图形、线段和角",
            human="几何图形是把现实物体抽象成点、线、面和体来研究。",
            why="后续平行线、三角形、圆和证明都建立在这些基本语言上。",
            terms={"点": "只表示位置。", "线": "表示延伸方向。", "面": "表示平铺的范围。"},
            prerequisites=["line_angle_basic", "volume"],
            next_topics=["parallel_lines", "triangle_basic", "circle"],
            examples=["把纸盒看成长方体", "把道路看成线段"],
            route=["现实物体", "抽象形状", "点线面体", "位置关系", "度量"],
            visuals=["实物模型", "展开图"],
        ),
        _point(
            topic_id="parallel_lines",
            name="相交线与平行线",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册",
            chapter="第五章 相交线与平行线",
            section="平行线的判定与性质",
            human="平行线是在同一平面内一直不相交的两条直线。",
            why="几何证明从平行线的角关系开始训练理由链。",
            terms={
                "同位角": "两条线被第三条线截出时位置相同的角。",
                "判定": "用条件说明它为什么成立。",
            },
            prerequisites=["line_angle_basic", "geometric_figures_intro"],
            next_topics=["triangle_basic", "congruent_triangles"],
            examples=["铁轨的两条边", "格纸上的平行线"],
            route=["相交", "角关系", "平行", "判定", "性质", "简单证明"],
            visuals=["截线图", "折纸"],
        ),
        _point(
            topic_id="coordinate_plane",
            name="平面直角坐标系",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册",
            chapter="第七章 平面直角坐标系",
            section="有序数对与坐标",
            human="坐标系用两个数确定平面上一个点的位置。",
            why="函数图像、几何变换和数据图都需要坐标语言。",
            terms={
                "横坐标": "表示左右位置的数。",
                "纵坐标": "表示上下位置的数。",
                "有序数对": "顺序不能换的一对数。",
            },
            prerequisites=["negative_number_intro", "rational_numbers"],
            next_topics=["function_intro", "linear_function", "quadratic_function"],
            examples=["座位第3列第5排", "地图定位"],
            route=["一条数轴定位", "两条数轴", "横纵方向", "有序数对", "点的位置"],
            visuals=["坐标纸", "地图网格"],
        ),
        _point(
            topic_id="real_numbers",
            name="实数",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册",
            chapter="第六章 实数",
            section="平方根、立方根和实数",
            human="实数把有理数和像根号2这样不能写成分数的数放在一起。",
            why="几何长度、坐标、函数和二次根式都需要实数范围。",
            terms={"平方根": "平方后得到原数的数。", "无理数": "不能写成两个整数之比的数。"},
            prerequisites=["rational_numbers", "power_scientific_notation"],
            next_topics=["quadratic_radicals", "pythagorean_theorem"],
            formulas=["sqrt(a)"],
            examples=["边长为1的正方形对角线是根号2"],
            route=["有理数", "开方", "数轴上的新点", "无理数", "实数"],
            visuals=["数轴", "正方形对角线"],
        ),
        _point(
            topic_id="linear_equation_systems",
            name="二元一次方程组",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册",
            chapter="第八章 二元一次方程组",
            section="消元法与实际问题",
            human="方程组是几个条件同时成立，解是同时满足它们的未知数取值。",
            why="它是从单个条件走向多条件建模的关键。",
            terms={"消元": "想办法先去掉一个未知数。", "公共解": "同时让所有方程成立的解。"},
            prerequisites=["linear_equation_two_variables", "linear_equation_one_variable"],
            next_topics=["linear_function"],
            formulas=["ax + by = c"],
            examples=["鸡兔同笼", "两种票价求人数"],
            route=["两个未知数", "两个条件", "同时成立", "消元", "检验"],
            visuals=["两条直线交点", "表格"],
        ),
        _point(
            topic_id="inequalities",
            name="一元一次不等式",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册",
            chapter="第九章 不等式与不等式组",
            section="不等式的性质与解集",
            human="不等式不是找一个答案，而是找一片能满足条件的数。",
            why="现实限制条件、取值范围和函数定义域都需要不等式。",
            terms={"解集": "所有能让不等式成立的数。", "不等号": "表示大于、小于等关系的符号。"},
            prerequisites=["absolute_value", "transposition"],
            next_topics=["inequality_systems"],
            formulas=["ax + b > c"],
            examples=["预算不超过100元", "身高大于某个标准"],
            route=["不相等关系", "等式性质类比", "变形", "解集", "数轴表示"],
            visuals=["数轴射线", "范围条"],
        ),
        _point(
            topic_id="inequality_systems",
            name="一元一次不等式组",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册",
            chapter="第九章 不等式与不等式组",
            section="不等式组",
            human="不等式组是多个范围条件同时满足，最后取它们重叠的部分。",
            why="多条件限制的应用题和函数取值范围都要用这种想法。",
            terms={"公共部分": "几个范围共同拥有的那一段。", "无解": "没有任何数能同时满足条件。"},
            prerequisites=["inequalities"],
            next_topics=["linear_function"],
            examples=["年龄至少12岁且不超过15岁", "价格在两个限制之间"],
            route=["一个范围", "多个范围", "画在同一数轴", "找重叠", "写解集"],
            visuals=["数轴重叠图"],
        ),
        _point(
            topic_id="data_collection_description",
            name="数据的收集、整理与描述",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册",
            chapter="第十章 数据的收集、整理与描述",
            section="全面调查、抽样调查和统计图",
            human="数据整理是在把零散信息变成能回答问题的证据。",
            why="统计不是画图作业，而是用数据判断现实问题。",
            terms={"样本": "从总体中选出的一部分。", "频数": "某类数据出现的次数。"},
            prerequisites=["data_collection_chart", "percent"],
            next_topics=["data_analysis", "probability"],
            examples=["调查睡眠时间", "统计出行方式"],
            route=["提出问题", "收集数据", "整理分类", "画图", "解释结论"],
            visuals=["频数表", "条形图", "扇形图"],
        ),
        _point(
            topic_id="triangle_basic",
            name="三角形",
            grade_band=GradeBand.JUNIOR,
            grade="八年级上册",
            chapter="第十一章 三角形",
            section="边、角、多边形内角和",
            human="三角形是由三条线段围成的最基本多边形。",
            why="几何证明、全等、相似和三角函数都从三角形开始。",
            terms={"内角": "三角形里面的角。", "高": "从顶点到对边的垂线段。"},
            prerequisites=["parallel_lines", "line_angle_basic"],
            next_topics=["congruent_triangles", "similar_triangles", "trigonometric_ratios"],
            formulas=["三角形内角和 = 180°"],
            examples=["屋架结构", "路标形状"],
            route=["三条边围成", "边角关系", "内角和", "多边形", "证明"],
            visuals=["拼角实验", "折纸"],
        ),
        _point(
            topic_id="congruent_triangles",
            name="全等三角形",
            grade_band=GradeBand.JUNIOR,
            grade="八年级上册",
            chapter="第十二章 全等三角形",
            section="全等三角形的判定",
            human="全等表示两个图形形状和大小都一样，可以完全重合。",
            why="它是初中几何证明中最重要的理由工具之一。",
            terms={"对应": "重合时互相配对的边或角。", "判定条件": "足够说明全等的一组信息。"},
            prerequisites=["triangle_basic"],
            next_topics=["axis_symmetry", "similar_triangles"],
            formulas=["SSS", "SAS", "ASA", "AAS", "HL"],
            examples=["证明两段长度相等", "判断两个零件是否一样"],
            route=["重合", "对应边角", "需要哪些条件", "判定", "推出结论"],
            visuals=["透明纸重叠", "边角标记图"],
        ),
        _point(
            topic_id="axis_symmetry",
            name="轴对称",
            grade_band=GradeBand.JUNIOR,
            grade="八年级上册",
            chapter="第十三章 轴对称",
            section="轴对称与等腰三角形",
            human="轴对称是沿一条线折过去，两边能完全重合。",
            why="它把图形直觉、全等证明和等腰三角形性质连起来。",
            terms={
                "对称轴": "折叠后两边重合的那条线。",
                "垂直平分线": "既垂直又平分一条线段的直线。",
            },
            prerequisites=["congruent_triangles"],
            next_topics=["rotation", "circle"],
            examples=["剪纸", "镜面对称"],
            route=["折叠", "重合", "对应点", "对称轴", "性质证明"],
            visuals=["折纸", "镜像图"],
        ),
        _point(
            topic_id="polynomial_multiplication",
            name="整式的乘法",
            grade_band=GradeBand.JUNIOR,
            grade="八年级上册",
            chapter="第十四章 整式的乘法与因式分解",
            section="整式的乘法",
            human="整式乘法是把每一部分按分配律逐个相乘再合并。",
            why="因式分解、分式、二次方程和函数表达式都要用它。",
            terms={"幂": "乘方得到的式子。", "展开": "把乘积变成加减形式。"},
            prerequisites=[
                "algebraic_expression",
                "distributive_property",
                "power_scientific_notation",
            ],
            next_topics=["factorization", "quadratic_equation"],
            formulas=["(a + b)(c + d) = ac + ad + bc + bd"],
            examples=["长方形面积展开", "平方差公式"],
            route=["单项式乘法", "分配律", "多项式乘法", "公式", "合并"],
            visuals=["面积模型"],
        ),
        _point(
            topic_id="factorization",
            name="因式分解",
            grade_band=GradeBand.JUNIOR,
            grade="八年级上册",
            chapter="第十四章 整式的乘法与因式分解",
            section="因式分解",
            human="因式分解是把一个加减式改写成几个因式相乘。",
            why="解方程、约分、函数零点都常靠把式子拆成乘积。",
            terms={"因式": "相乘中的每一块。", "公因式": "每一项都共同含有的因式。"},
            prerequisites=["polynomial_multiplication", "like_terms"],
            next_topics=["rational_expression", "quadratic_equation"],
            formulas=["a^2 - b^2 = (a + b)(a - b)"],
            examples=["把面积和拆成长宽乘积", "提取共同因数"],
            route=["乘法反过来", "找公因式", "公式结构", "乘回去检查"],
            visuals=["面积拼图", "式子颜色标记"],
        ),
        _point(
            topic_id="rational_expression",
            name="分式",
            grade_band=GradeBand.JUNIOR,
            grade="八年级上册",
            chapter="第十五章 分式",
            section="分式、分式运算和分式方程",
            human="分式像分数，只是分子或分母里可以有字母。",
            why="它让学生用代数方式表达比例、速度和反比例关系。",
            terms={"分式": "分母中含有字母的式子。", "最简分式": "不能再约分的分式。"},
            prerequisites=["fraction_operations", "factorization"],
            next_topics=["inverse_proportion_function"],
            formulas=["A/B, B != 0"],
            examples=["路程除以速度表示时间", "工作效率问题"],
            route=["分数", "字母进入分母", "分母不能为0", "约分", "方程"],
            visuals=["分数类比表", "关系表"],
        ),
        _point(
            topic_id="quadratic_radicals",
            name="二次根式",
            grade_band=GradeBand.JUNIOR,
            grade="八年级下册",
            chapter="第十六章 二次根式",
            section="二次根式的性质与运算",
            human="二次根式是在表示某个非负数的平方根。",
            why="勾股定理、距离公式和二次方程都离不开根式。",
            terms={"被开方数": "根号里面的数。", "最简二次根式": "已经化到最简单的根式。"},
            prerequisites=["real_numbers"],
            next_topics=["pythagorean_theorem", "quadratic_equation"],
            formulas=["sqrt(a), a >= 0"],
            examples=["正方形面积为2时边长是根号2"],
            route=["平方", "反过来开方", "非负", "化简", "运算"],
            visuals=["正方形面积", "数轴"],
        ),
        _point(
            topic_id="pythagorean_theorem",
            name="勾股定理",
            grade_band=GradeBand.JUNIOR,
            grade="八年级下册",
            chapter="第十七章 勾股定理",
            section="直角三角形三边关系",
            human="勾股定理说明直角三角形两条直角边的平方和等于斜边的平方。",
            why="它把图形长度和代数计算连起来，是坐标距离和三角函数的基础。",
            terms={"直角边": "夹成直角的两条边。", "斜边": "直角对面的那条边。"},
            prerequisites=["triangle_basic", "quadratic_radicals", "area"],
            next_topics=["trigonometric_ratios", "coordinate_plane"],
            formulas=["a^2 + b^2 = c^2"],
            examples=["求梯子长度", "判断三角形是否为直角三角形"],
            route=["直角三角形", "边上的正方形", "面积关系", "平方和", "求长度"],
            visuals=["正方形拼图", "网格距离"],
        ),
        _point(
            topic_id="parallelogram",
            name="平行四边形",
            grade_band=GradeBand.JUNIOR,
            grade="八年级下册",
            chapter="第十八章 平行四边形",
            section="平行四边形、矩形、菱形和正方形",
            human="平行四边形是两组对边分别平行的四边形。",
            why="它承接平行线和全等证明，也为面积与向量直觉打底。",
            terms={"对边": "不相邻、相对的两条边。", "对角线": "连接不相邻两个顶点的线段。"},
            prerequisites=["parallel_lines", "congruent_triangles"],
            next_topics=["similar_triangles"],
            formulas=["平行四边形面积 = 底 x 高"],
            examples=["伸缩门", "瓷砖图案"],
            route=["四边形", "两组平行", "性质", "判定", "特殊平行四边形"],
            visuals=["格纸", "活动四边形模型"],
        ),
        _point(
            topic_id="linear_function",
            name="一次函数",
            grade_band=GradeBand.JUNIOR,
            grade="八年级下册",
            chapter="第十九章 一次函数",
            section="函数、正比例函数和一次函数",
            human="一次函数描述一种稳定的线性变化：每多一点输入，输出按固定速度变。",
            why="它是学生第一次系统把表格、图像和表达式统一起来。",
            terms={"斜率": "图像倾斜程度，也表示变化速度。", "截距": "图像和坐标轴相交的位置。"},
            prerequisites=[
                "function_intro",
                "coordinate_plane",
                "proportion",
                "linear_equation_systems",
            ],
            next_topics=["quadratic_function", "inverse_proportion_function"],
            formulas=["y = kx + b"],
            examples=["打车费用", "水位匀速上升"],
            route=["两个变量", "表格", "坐标点", "直线", "表达式", "变化速度"],
            visuals=["表格", "坐标图像"],
        ),
        _point(
            topic_id="data_analysis",
            name="数据的分析",
            grade_band=GradeBand.JUNIOR,
            grade="八年级下册",
            chapter="第二十章 数据的分析",
            section="平均数、中位数、众数和方差",
            human="数据分析是在用几个代表性指标看一组数据的水平和波动。",
            why="真实世界的数据不能只看一个数字，要知道代表性和稳定性。",
            terms={"中位数": "按大小排好后中间的数。", "方差": "描述数据离平均数有多分散。"},
            prerequisites=["average", "data_collection_description"],
            next_topics=["probability"],
            formulas=["平均数", "方差"],
            examples=["比较两组成绩是否稳定", "分析气温变化"],
            route=["一组数据", "整体水平", "中间位置", "最常出现", "波动大小"],
            visuals=["点图", "箱线直觉图"],
        ),
        _point(
            topic_id="quadratic_equation",
            name="一元二次方程",
            grade_band=GradeBand.JUNIOR,
            grade="九年级上册",
            chapter="第二十一章 一元二次方程",
            section="一元二次方程及其解法",
            human="一元二次方程是未知数最高次数为2的方程。",
            why="面积问题、抛物线、增长模型都会自然产生二次方程。",
            terms={"二次项": "含未知数平方的项。", "根": "让方程成立的未知数取值。"},
            prerequisites=["factorization", "quadratic_radicals", "power_scientific_notation"],
            next_topics=["quadratic_function"],
            formulas=["ax^2 + bx + c = 0"],
            examples=["已知矩形面积求边长", "抛物线与地面的交点"],
            route=["平方项", "标准形式", "因式分解", "配方", "公式", "检验"],
            visuals=["面积模型", "抛物线交点"],
        ),
        _point(
            topic_id="quadratic_function",
            name="二次函数",
            grade_band=GradeBand.JUNIOR,
            grade="九年级上册",
            chapter="第二十二章 二次函数",
            section="二次函数的图象和性质",
            human="二次函数描述输出里含有输入平方的变化，图像通常是一条抛物线。",
            why="它把方程、图像、最值和现实建模合在一起。",
            terms={"抛物线": "二次函数常见的U形图像。", "顶点": "抛物线最高或最低的位置。"},
            prerequisites=["linear_function", "quadratic_equation", "coordinate_plane"],
            next_topics=[],
            formulas=["y = ax^2 + bx + c"],
            examples=["抛球高度变化", "围栏面积最大问题"],
            route=["平方变化", "列表", "画点", "抛物线", "顶点", "最值"],
            visuals=["坐标图像", "动态表格"],
        ),
        _point(
            topic_id="rotation",
            name="旋转",
            grade_band=GradeBand.JUNIOR,
            grade="九年级上册",
            chapter="第二十三章 旋转",
            section="图形旋转和中心对称",
            human="旋转是图形绕着一个点按固定角度转动。",
            why="它补齐初中图形变换，也帮助理解圆和对称。",
            terms={"旋转中心": "图形围绕转动的点。", "旋转角": "转过的角度。"},
            prerequisites=["axis_symmetry", "coordinate_plane"],
            next_topics=["circle"],
            examples=["风车转动", "钟表指针"],
            route=["固定点", "转动方向", "角度", "对应点", "中心对称"],
            visuals=["旋转纸片", "坐标变换图"],
        ),
        _point(
            topic_id="circle",
            name="圆",
            grade_band=GradeBand.JUNIOR,
            grade="九年级上册",
            chapter="第二十四章 圆",
            section="圆的性质、位置关系和正多边形",
            human="圆是到同一个中心点距离都相等的点组成的图形。",
            why="圆把距离、角、对称和实际测量集中在一起。",
            terms={
                "圆心": "圆中间的固定点。",
                "半径": "圆心到圆上任意一点的线段。",
                "弦": "连接圆上两点的线段。",
            },
            prerequisites=["geometric_figures_intro", "rotation", "pythagorean_theorem"],
            next_topics=["trigonometric_ratios"],
            formulas=["C = 2πr", "S = πr^2"],
            examples=["车轮", "钟面"],
            route=["定点", "定长", "圆周", "圆心角", "位置关系", "计算"],
            visuals=["圆规作图", "旋转半径"],
        ),
        _point(
            topic_id="probability",
            name="概率初步",
            grade_band=GradeBand.JUNIOR,
            grade="九年级上册",
            chapter="第二十五章 概率初步",
            section="随机事件、列举法和频率估计概率",
            human="概率是在描述一件事发生的可能性有多大。",
            why="它让学生用数量而不是感觉判断不确定事件。",
            terms={"随机事件": "可能发生也可能不发生的事件。", "样本空间": "所有可能结果的集合。"},
            prerequisites=["fraction", "percent", "data_collection_description"],
            next_topics=[],
            formulas=["概率 = 有利结果数 ÷ 所有等可能结果数"],
            examples=["掷骰子", "抽签"],
            route=["可能或不可能", "所有结果", "有利结果", "比例", "频率估计"],
            visuals=["树状图", "列表"],
        ),
        _point(
            topic_id="similar_triangles",
            name="相似三角形",
            grade_band=GradeBand.JUNIOR,
            grade="九年级下册",
            chapter="第二十七章 相似",
            section="相似三角形的判定和性质",
            human="相似表示形状一样、大小可以不同。",
            why="比例、缩放、测量和三角函数都建立在相似思想上。",
            terms={"相似比": "对应边长度的比。", "对应角": "形状匹配时相互对应的角。"},
            prerequisites=["ratio", "triangle_basic", "congruent_triangles"],
            next_topics=["trigonometric_ratios"],
            formulas=["对应边成比例，对应角相等"],
            examples=["地图和真实地形", "影子测高"],
            route=["放大缩小", "形状不变", "对应角", "对应边比", "判定"],
            visuals=["缩放图", "网格图"],
        ),
        _point(
            topic_id="trigonometric_ratios",
            name="锐角三角函数",
            grade_band=GradeBand.JUNIOR,
            grade="九年级下册",
            chapter="第二十八章 锐角三角函数",
            section="正弦、余弦、正切",
            human="锐角三角函数是在直角三角形里，用边长的比描述一个角。",
            why="它把角度和长度联系起来，可用于测高、测距和后续数学学习。",
            terms={
                "正弦": "对边和斜边的比。",
                "余弦": "邻边和斜边的比。",
                "正切": "对边和邻边的比。",
            },
            prerequisites=["similar_triangles", "pythagorean_theorem", "ratio"],
            next_topics=[],
            formulas=["sin A", "cos A", "tan A"],
            examples=["测楼高", "坡度"],
            route=["直角三角形", "固定锐角", "相似保证比不变", "三种边长比", "测量"],
            visuals=["直角三角形标边", "测高示意图"],
        ),
        _point(
            topic_id="inverse_proportion_function",
            name="反比例函数",
            grade_band=GradeBand.JUNIOR,
            grade="九年级下册",
            chapter="第二十六章 反比例函数",
            section="反比例函数的图象和性质",
            human="反比例函数描述两个量相乘保持不变时的变化关系。",
            why="它让比例从小学算术进入坐标图像和函数语言。",
            terms={"常数k": "乘积保持不变的那个数。", "双曲线": "反比例函数常见的两支曲线图像。"},
            prerequisites=[
                "proportion",
                "rational_expression",
                "coordinate_plane",
                "function_intro",
            ],
            next_topics=[],
            formulas=["y = k/x"],
            examples=["总路程一定时速度和时间", "面积一定时长和宽"],
            route=["乘积不变", "表格", "坐标点", "曲线", "实际限制"],
            visuals=["表格", "坐标图像"],
        ),
        _point(
            topic_id="number_comparison",
            name="数的大小比较",
            grade_band=GradeBand.PRIMARY,
            grade="一年级上册至二年级下册",
            chapter="数的认识",
            section="比较多少与大小",
            human="比较大小是在判断两个数量谁多、谁少，或者在数轴上谁更靠后。",
            why="后面估算、排序、分数小数比较和不等式都要先会比较。",
            terms={"大于": "比另一个数多。", "小于": "比另一个数少。"},
            prerequisites=["number_recognition"],
            next_topics=["place_value_decimal_system", "inequalities"],
            examples=["比较两盒彩笔谁多", "按身高排队"],
            route=["一一对应", "多少", "数轴位置", "大于小于符号"],
            visuals=["点子图", "数轴"],
        ),
        _point(
            topic_id="rounding_estimation",
            name="估算与近似数",
            grade_band=GradeBand.PRIMARY,
            grade="二年级下册至四年级上册",
            chapter="万以内数的认识 / 大数的认识",
            section="近似数和估算",
            human="估算是先得到一个接近真实结果、方便判断的数。",
            why="学生做应用题和复杂计算时，需要先判断答案是否合理。",
            terms={
                "近似数": "接近准确值、方便使用的数。",
                "四舍五入": "按后一位决定保留位是否进一。",
            },
            prerequisites=["place_value_decimal_system", "number_comparison"],
            next_topics=["decimal_operations", "data_analysis"],
            examples=["估一下一箱书大约多重", "判断计算结果是不是离谱"],
            route=["准确数", "接近", "保留到某一位", "估算检验"],
            visuals=["数轴", "区间条"],
        ),
        _point(
            topic_id="multiplication_table",
            name="乘法口诀",
            grade_band=GradeBand.PRIMARY,
            grade="二年级上册至二年级下册",
            chapter="表内乘法",
            section="乘法口诀",
            human="乘法口诀是把常见的相同组数量结果记熟，方便快速计算。",
            why="多位数乘除、面积、比例和函数数值计算都会频繁用到。",
            terms={"口诀": "把常用结果压缩成容易记住的句子。"},
            prerequisites=["multiplication_meaning"],
            next_topics=["integer_multiplication_division", "area"],
            examples=["三四十二表示3组4一共12", "算4排每排6人"],
            route=["相同组", "重复加法", "阵列", "口诀", "快速计算"],
            visuals=["九九表", "阵列图"],
        ),
        _point(
            topic_id="integer_multiplication_division",
            name="整数乘除法",
            grade_band=GradeBand.PRIMARY,
            grade="三年级上册至四年级上册",
            chapter="多位数乘一位数 / 除数是一位数的除法",
            section="笔算乘除法",
            human="整数乘除法是在更大的数里处理相同组和平均分。",
            why="面积、体积、比例、速度和代数计算都离不开整数乘除。",
            terms={
                "笔算": "按数位一步一步写下来的计算。",
                "余数": "平均分后剩下不够再分的一部分。",
            },
            prerequisites=[
                "place_value_decimal_system",
                "multiplication_table",
                "division_meaning",
            ],
            next_topics=["mixed_operations", "fraction_operations"],
            examples=["24盒彩笔每盒12支", "96本书平均分到8个班"],
            route=["相同组", "按位乘除", "进位退位", "验算"],
            visuals=["数位表", "分组图"],
        ),
        _point(
            topic_id="division_with_remainder",
            name="有余数的除法",
            grade_band=GradeBand.PRIMARY,
            grade="二年级下册至三年级上册",
            chapter="有余数的除法",
            section="余数的意义",
            human="有余数的除法是在平均分后，还剩下一些不够再分成一整组。",
            why="它帮助学生理解除法不是永远整除，也为分数和取整问题打底。",
            terms={"余数": "平均分后剩下的数量。", "整除": "没有剩下的除法情况。"},
            prerequisites=["division_meaning"],
            next_topics=["fraction", "integer_multiplication_division"],
            examples=["17颗糖每人分5颗，还剩2颗", "装箱后剩几件"],
            route=["平均分", "每组一样多", "剩下", "余数小于除数"],
            visuals=["实物分组", "线段图"],
        ),
        _point(
            topic_id="unit_conversion",
            name="单位换算",
            grade_band=GradeBand.PRIMARY,
            grade="二年级上册至五年级下册",
            chapter="常见量 / 面积单位 / 体积单位",
            section="长度、质量、时间、面积和体积单位换算",
            human="单位换算是在用不同单位说同一个量。",
            why="不懂单位，应用题、面积体积和速度问题都会看错数量。",
            terms={
                "单位进率": "两个单位之间相差多少倍。",
                "同一个量": "东西没有变，只是说法变了。",
            },
            prerequisites=["measurement_units", "place_value_decimal_system"],
            next_topics=["area", "volume", "rate_speed_distance"],
            examples=["1米等于100厘米", "1平方米等于10000平方厘米"],
            route=["量什么", "单位", "进率", "乘或除", "检验大小"],
            visuals=["单位阶梯", "尺子"],
        ),
        _point(
            topic_id="rectangle_square_features",
            name="长方形和正方形",
            grade_band=GradeBand.PRIMARY,
            grade="三年级上册",
            chapter="长方形和正方形",
            section="边和角的特征",
            human="长方形和正方形用边长和直角描述规则的四边形。",
            why="它们是周长、面积、体积和坐标图像的基本形状。",
            terms={"对边": "相对的两条边。", "直角": "像课本角一样正正的角。"},
            prerequisites=["line_angle_basic"],
            next_topics=["perimeter", "area", "parallelogram"],
            examples=["课桌面", "方格纸中的小格"],
            route=["四条边", "四个角", "对边相等", "正方形是特殊长方形"],
            visuals=["方格纸", "折纸"],
        ),
        _point(
            topic_id="primary_circle_features",
            name="圆的初步认识",
            grade_band=GradeBand.PRIMARY,
            grade="六年级上册",
            chapter="圆",
            section="圆的认识、周长和面积",
            human="圆是到同一个中心点距离都一样远的一圈点。",
            why="初中圆、旋转、角度和几何证明都需要先有圆的直觉。",
            terms={"半径": "圆心到圆上一点的线段。", "直径": "经过圆心、两端在圆上的线段。"},
            prerequisites=["line_angle_basic", "measurement_units"],
            next_topics=["circle"],
            formulas=["C = 2πr", "S = πr^2"],
            examples=["车轮", "钟面"],
            route=["定点", "定长", "一圈点", "半径", "周长和面积"],
            visuals=["圆规作图", "绳子绕圆"],
        ),
        _point(
            topic_id="equation_applications_primary",
            name="简易方程应用",
            grade_band=GradeBand.PRIMARY,
            grade="五年级上册",
            chapter="简易方程",
            section="列方程解决问题",
            human="列方程是把题目里的相等关系写成含未知数的等式。",
            why="初中的方程和函数建模都从这里开始。",
            terms={"未知量": "题目里还不知道、需要求的量。", "等量关系": "两边一样多的关系。"},
            prerequisites=["primary_equation", "quantity_relationship"],
            next_topics=["linear_equation_one_variable", "linear_equation_applications"],
            examples=["已知总价和单价求数量", "已知周长求边长"],
            route=["找未知量", "找相等关系", "列方程", "解方程", "检验"],
            visuals=["线段图", "天平模型"],
        ),
        _point(
            topic_id="rate_speed_distance",
            name="速度、时间和路程",
            grade_band=GradeBand.PRIMARY,
            grade="五年级上册至六年级下册",
            chapter="小数乘除法 / 比和比例",
            section="行程问题",
            human="速度是在说单位时间里走了多少路。",
            why="它是比例、一次函数和应用题建模的常见入口。",
            terms={"速度": "每一份时间走过的路程。", "单位时间": "被当作一份的时间。"},
            prerequisites=["decimal_operations", "quantity_relationship", "unit_conversion"],
            next_topics=["proportion", "linear_function"],
            formulas=["路程 = 速度 x 时间"],
            examples=["每小时60千米开3小时", "每分钟走80米"],
            route=["路程", "时间", "每份时间", "速度", "三量关系"],
            visuals=["线段图", "表格"],
        ),
        _point(
            topic_id="scale_ratio_application",
            name="比例尺",
            grade_band=GradeBand.PRIMARY,
            grade="六年级下册",
            chapter="比例",
            section="比例尺",
            human="比例尺是在说图上距离和实际距离按同一个比缩小或放大。",
            why="它连接比、比例、相似图形和现实测量。",
            terms={"图上距离": "图里量到的距离。", "实际距离": "现实里的真实距离。"},
            prerequisites=["ratio", "proportion", "unit_conversion"],
            next_topics=["similar_triangles"],
            formulas=["比例尺 = 图上距离 : 实际距离"],
            examples=["地图上1厘米表示实际1千米", "按比例画教室平面图"],
            route=["两个距离", "同单位", "比", "放大缩小", "实际计算"],
            visuals=["地图", "双数轴"],
        ),
        _point(
            topic_id="remove_parentheses",
            name="去括号",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第二章 整式的加减",
            section="去括号与添括号",
            human="去括号是在不改变式子意思的前提下，把括号里的项放出来。",
            why="合并同类项、解方程和整式乘法前经常要先处理括号。",
            terms={"符号": "项前面的加号或减号。", "添括号": "把几项重新合成一组。"},
            prerequisites=["algebraic_expression", "distributive_property"],
            next_topics=["like_terms", "linear_equation_one_variable"],
            examples=["3-(x+2)不能直接写成3-x+2", "把总价拆成几部分"],
            route=["括号是一组", "前面是加号", "前面是减号", "符号变化", "合并"],
            visuals=["颜色标注式子", "面积模型"],
        ),
        _point(
            topic_id="linear_equation_applications",
            name="一元一次方程应用",
            grade_band=GradeBand.JUNIOR,
            grade="七年级上册",
            chapter="第三章 一元一次方程",
            section="实际问题与一元一次方程",
            human="方程应用是在把现实条件翻译成一个能求未知数的等式。",
            why="学生不会应用题时，常卡在找量和关系，而不是卡在计算。",
            terms={"设未知数": "先给不知道的量起一个字母名字。", "检验": "把答案放回原题检查。"},
            prerequisites=["linear_equation_one_variable", "quantity_relationship"],
            next_topics=["linear_equation_systems", "linear_function"],
            examples=["打折销售", "工程合作", "行程追及"],
            route=["读题", "找量", "设未知数", "列等式", "解和检验"],
            visuals=["表格", "线段图"],
        ),
        _point(
            topic_id="geometric_proof_intro",
            name="几何证明入门",
            grade_band=GradeBand.JUNIOR,
            grade="七年级下册至八年级上册",
            chapter="相交线与平行线 / 三角形",
            section="证明理由链",
            human="证明是在把每一步为什么成立说清楚。",
            why="初中几何不是只看图猜结论，而是要用已知条件推出结论。",
            terms={"已知": "题目已经告诉你的条件。", "结论": "需要说明成立的结果。"},
            prerequisites=["parallel_lines", "triangle_basic"],
            next_topics=["congruent_triangles", "similar_triangles"],
            examples=["证明两个角相等", "证明两条线平行"],
            route=["看图", "找已知", "找要证", "每步有理由", "写成证明"],
            visuals=["理由链", "图形标注"],
        ),
        _point(
            topic_id="function_graph_reading",
            name="函数图像读法",
            grade_band=GradeBand.JUNIOR,
            grade="八年级下册",
            chapter="第十九章 一次函数",
            section="函数图象",
            human="读函数图像是在从点、线和变化趋势里看两个量的关系。",
            why="不会读图，就很难理解一次函数、反比例函数和二次函数。",
            terms={"横轴": "通常表示输入量的方向。", "纵轴": "通常表示输出量的方向。"},
            prerequisites=["function_intro", "coordinate_plane"],
            next_topics=["linear_function", "quadratic_function"],
            examples=["看水位随时间变化", "看费用随里程变化"],
            route=["横轴纵轴", "点表示一组值", "线表示变化", "上升下降", "读实际意义"],
            visuals=["坐标图像", "变化故事"],
        ),
        _point(
            topic_id="probability_tree_listing",
            name="列表法与树状图",
            grade_band=GradeBand.JUNIOR,
            grade="九年级上册",
            chapter="第二十五章 概率初步",
            section="列举所有可能结果",
            human="列表法和树状图是在把所有可能结果有顺序地列全。",
            why="概率题常错在漏数或重复数，不是只错在公式。",
            terms={"列举": "一个一个列出来。", "重复": "同一个结果被数了多次。"},
            prerequisites=["probability"],
            next_topics=[],
            examples=["抛两枚硬币", "从两个袋子各取一个球"],
            route=["一次选择", "第二次选择", "所有分支", "不漏不重", "算比例"],
            visuals=["树状图", "表格"],
        ),
    ]
