"""Extra primary/junior topics to densify the learning graph.

Content is original plain-language teaching text aligned with typical
Chinese compulsory-education math strands (number, algebra, geometry,
functions, statistics). It is NOT a copy of any commercial textbook page.
Structure references open knowledge-graph practice (prerequisite edges,
term glossary first) described in docs/content-sources.md.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping

from math_learning_graph.depth import (
    default_layers,
    default_practice_ladder,
    default_reflection_questions,
    default_worked_examples,
)
from math_learning_graph.models import (
    GradeBand,
    KnowledgePoint,
    PracticeTask,
    TextbookPosition,
    WorkedExample,
)

CURRICULUM = "人教版义务教育数学（理解扩充）"


def _position(grade: str, chapter: str, section: str) -> TextbookPosition:
    return TextbookPosition(
        curriculum=CURRICULUM,
        grade=grade,
        chapter=chapter,
        section=section,
    )


def _worked(title: str, problem: str, steps: list[str], check: str) -> WorkedExample:
    return WorkedExample(title=title, problem=problem, steps=steps, answer_check=check)


def _task(level: str, prompt: str, goal: str) -> PracticeTask:
    return PracticeTask(level=level, prompt=prompt, goal=goal)


def _point(
    *,
    topic_id: str,
    name: str,
    grade_band: GradeBand,
    grade: str,
    chapter: str,
    section: str,
    human: str,
    why: str,
    terms: Mapping[str, str],
    formal: str = "",
    prerequisites: Iterable[str] = (),
    next_topics: Iterable[str] = (),
    formulas: Iterable[str] = (),
    examples: Iterable[str] = (),
    route: Iterable[str] = (),
    misconceptions: Iterable[str] = (),
    visuals: Iterable[str] = (),
    exercise_types: Iterable[str] = (),
    conceptual_layers: Iterable[str] = (),
    worked_examples: Iterable[WorkedExample] = (),
    practice_ladder: Iterable[PracticeTask] = (),
    reflection_questions: Iterable[str] = (),
) -> KnowledgePoint:
    route_items = list(route)
    formal_text = formal or (
        f"在课本里，「{name}」用来描述：{human}"
    )
    point = KnowledgePoint(
        id=topic_id,
        name=name,
        grade_band=grade_band,
        textbook_positions=[_position(grade, chapter, section)],
        human_explanation=human,
        life_examples=list(examples),
        why_needed=why,
        formal_definition=formal_text,
        term_explanations=dict(terms),
        misconceptions=list(misconceptions)
        or [
            f"只背「{name}」这个词，却说不出它在处理什么关系。",
            "用一个没解释过的新词去解释另一个新词。",
        ],
        prerequisite_ids=list(prerequisites),
        next_ids=list(next_topics),
        formulas=list(formulas),
        visualization_methods=list(visuals) or ["画图", "列表", "举生活例子"],
        ai_teaching_hints=[
            "永远先拆词：学生可能不认识你随口说出的术语。",
            "先问：卡在哪个词，还是卡在哪一步？",
            "每用一个新符号，先说它代表什么。",
        ],
        exercise_types=list(exercise_types) or ["解释词", "举例子", "判断对错", "小步练习"],
        school_route=[grade, chapter, section],
        understanding_route=route_items
        or ["先弄懂词", "看在比什么/算什么", "举例子", "再看课本说法"],
    )
    return point.model_copy(
        update={
            "conceptual_layers": list(conceptual_layers) or default_layers(point),
            "worked_examples": list(worked_examples) or default_worked_examples(point),
            "practice_ladder": list(practice_ladder) or default_practice_ladder(name),
            "reflection_questions": list(reflection_questions)
            or default_reflection_questions(name),
        },
    )


def load_expanded_knowledge_points() -> list[KnowledgePoint]:
    p, j, b = GradeBand.PRIMARY, GradeBand.JUNIOR, GradeBand.BRIDGE
    return [
        # —— 小学：数与运算加厚 ——
        _point(
            topic_id="zero_and_placeholder",
            name="0 的意义与占位",
            grade_band=p,
            grade="一年级上册至二年级",
            chapter="1～20 的认识 / 100 以内的数",
            section="0 表示没有与占位",
            human="0 既可以表示「一个都没有」，也可以在多位数里占住某个位置，让别的数字站对地方。",
            why="没有 0 的占位，10、101、1001 这类数就写不清楚。",
            terms={
                "0": "可以表示没有；在多位数里也可以占位置。",
                "占位": "让数字站在正确的数位上，即使这一位是「空的」。",
            },
            formal="0 是自然数中表示「没有」的数；在十进制记数里也用于表示某数位上没有单位。",
            prerequisites=["number_recognition", "place_value_decimal_system"],
            next_topics=["integer_addition_subtraction", "decimal"],
            examples=["篮子里没有苹果写成 0", "305 的十位是 0，表示没有整十"],
            route=["没有", "写 0", "多位数空位", "占位", "读数"],
            misconceptions=["以为 0 没有用", "把 0 随便删掉导致数变了"],
            visuals=["空篮子", "数位表空格"],
            worked_examples=[
                _worked(
                    "为什么 305 不能写成 35",
                    "305 里的 0 在说什么？",
                    [
                        "先看百位：3 表示 3 个百。",
                        "十位是 0：表示「没有整十」，但位置还在。",
                        "个位 5：5 个一。",
                        "若删掉 0 变成 35，就只剩 3 个十和 5 个一，意思完全变了。",
                    ],
                    "能说出 0 在这里是占位，不是可有可无的装饰。",
                )
            ],
            practice_ladder=[
                _task(
                    "看懂",
                    "用自己的话说：0 什么时候表示没有，什么时候表示占位？",
                    "分清两种用法。",
                ),
                _task("会做", "比较 204 和 240，指出 0 各在哪一位。", "结合数位。"),
                _task("迁移", "小数 2.05 里的 0 在占什么位置？", "把占位迁到小数。"),
            ],
            reflection_questions=[
                "如果没有 0，10 该怎么写？",
                "「没有」和「占位」有什么不同？",
            ],
        ),
        _point(
            topic_id="odd_even_numbers",
            name="奇数与偶数",
            grade_band=p,
            grade="一年级下册至二年级",
            chapter="分类与数的性质初步",
            section="单数双数",
            human="能两个两个正好分完的是偶数；会剩下 1 个的是奇数。",
            why="配对、整除、质数偶偶性等后面的性质都从这里起步。",
            terms={
                "偶数": "能平均分成两个一样多、且正好分完的整数（个位是 0、2、4、6、8）。",
                "奇数": "两个两个分会剩 1 个的整数（个位是 1、3、5、7、9）。",
            },
            formal="能被 2 整除的整数叫偶数；不能被 2 整除的整数叫奇数。",
            prerequisites=["number_recognition", "division_meaning"],
            next_topics=["factors_multiples", "integer_multiplication_division"],
            examples=["12 个同学两两握手刚好分完", "11 个苹果两个两个拿会剩 1 个"],
            route=["两个两个分", "分完或剩 1", "看个位", "奇偶名字"],
            visuals=["配对圈", "数轴上跳 2"],
        ),
        _point(
            topic_id="factors_multiples",
            name="因数与倍数",
            grade_band=p,
            grade="五年级上册",
            chapter="因数与倍数",
            section="因数、倍数、质数合数",
            human="如果 A 乘某整数正好得到 B，就说 A 是 B 的因数，B 是 A 的倍数。",
            why="约分、通分、最小公倍数、质因数分解都靠它。",
            terms={
                "因数": "能整除某个数的整数（在小学正整数范围内讨论）。",
                "倍数": "某个数乘整数得到的结果。",
                "质数": "大于 1，并且只有 1 和它本身两个因数的数。",
                "合数": "大于 1，并且因数超过两个的数。",
            },
            formal="若存在整数 k 使 a×k=b，则 a 是 b 的因数，b 是 a 的倍数。",
            prerequisites=["multiplication_meaning", "division_meaning", "odd_even_numbers"],
            next_topics=["gcd_lcm", "fraction_operations", "factorization"],
            formulas=["a | b 表示 a 整除 b（后续会见到）"],
            examples=["12 的因数有 1、2、3、4、6、12", "3 的倍数：3、6、9、12…"],
            route=["整除", "谁乘谁得谁", "列因数", "质数合数", "后面约分要用"],
            misconceptions=["把质数和奇数混为一谈", "以为 1 是质数"],
            visuals=["矩形拆分", "因数对"],
            worked_examples=[
                _worked(
                    "找 18 的因数",
                    "18 能被哪些正整数整除？",
                    [
                        "从 1 试到 18：1×18、2×9、3×6。",
                        "4 不行，5 不行…",
                        "写成从小到大：1、2、3、6、9、18。",
                        "成对出现，不容易漏。",
                    ],
                    "能成对列出，并说明「整除」是什么意思。",
                )
            ],
        ),
        _point(
            topic_id="gcd_lcm",
            name="最大公因数与最小公倍数",
            grade_band=p,
            grade="五年级上册",
            chapter="因数与倍数",
            section="最大公因数、最小公倍数",
            human="最大公因数是几个数「都能被整除」的数里最大的那个；最小公倍数是几个数「都能整除它」的数里最小的那个。",
            why="约分靠最大公因数，通分靠最小公倍数。",
            terms={
                "最大公因数": "几个数的公共因数里最大的。",
                "最小公倍数": "几个数的公共倍数里最小的。",
                "公约数": "几个数共同的因数。",
            },
            formal="正整数 a、b 的最大公因数记作 gcd(a,b)；最小公倍数记作 lcm(a,b)。",
            prerequisites=["factors_multiples", "fraction"],
            next_topics=["fraction_operations", "ratio"],
            examples=["12 和 18 的最大公因数是 6", "4 和 6 的最小公倍数是 12"],
            route=["先找因数/倍数", "找公共的", "取最大/最小", "用到约分通分"],
            visuals=["集合圈", "数轴标记倍数"],
        ),
        _point(
            topic_id="time_and_elapsed",
            name="时间与经过时间",
            grade_band=p,
            grade="一年级下册至三年级",
            chapter="认识时间",
            section="时、分、秒与经过时间",
            human="时间是在说「什么时候」和「过了多久」；钟面把一圈分成 60 小格来量。",
            why="行程问题、作息和函数里的「自变量是时间」都要用。",
            terms={
                "时": "较大的时间单位，1 时 = 60 分。",
                "分": "1 分 = 60 秒。",
                "经过时间": "从开始到结束中间过了多久。",
            },
            formal="时间计量采用六十进制：1 时=60 分，1 分=60 秒。",
            prerequisites=["number_recognition", "measurement_units"],
            next_topics=["rate_speed_distance", "unit_conversion"],
            examples=["从 8:20 到 9:05 过了多久", "一节课 40 分钟"],
            route=["读钟面", "开始时刻", "结束时刻", "相减得经过", "注意借位 60"],
            misconceptions=["把时间当十进制直接减", "分针格数和分钟混淆"],
            visuals=["钟面", "时间线段"],
        ),
        _point(
            topic_id="money_calculation",
            name="人民币与简单计算",
            grade_band=p,
            grade="一年级下册至二年级",
            chapter="认识人民币",
            section="元角分与找零",
            human="钱是用「元、角、分」表示的数量；买东西是在做加减，找零是在算差。",
            why="小数、百分数折扣和实际应用都从货币量感长出来。",
            terms={
                "元": "人民币的基本单位。",
                "角": "1 元 = 10 角。",
                "找零": "付出的钱减去应付的钱。",
            },
            formal="人民币主单位是元，1 元=10 角=100 分。",
            prerequisites=["integer_addition_subtraction", "decimal"],
            next_topics=["decimal_operations", "percent"],
            examples=["3 元 5 角写成 3.5 元", "付 10 元买 6.5 元商品"],
            route=["认识面额", "换算", "合计", "找零"],
            visuals=["钱币图", "价签"],
        ),
        _point(
            topic_id="bar_line_pie_charts",
            name="条形图、折线图与扇形图",
            grade_band=p,
            grade="四年级至六年级",
            chapter="统计",
            section="常见统计图",
            human="统计图是用图形高度、折线起伏或扇形大小，把「谁多谁少、怎么变化、占多少」一眼看出来。",
            why="不会读图，就读不懂新闻数据和函数图像的前身。",
            terms={
                "条形图": "用直条长短比数量。",
                "折线图": "用折线看随时间或顺序的变化。",
                "扇形图": "用圆的各块表示各部分占整体的多少。",
            },
            formal="条形统计图、折线统计图、扇形统计图是小学常见的数据直观表示方式。",
            prerequisites=["data_collection_chart", "average", "percent"],
            next_topics=["data_analysis", "probability"],
            examples=["各班人数条形图", "一周气温折线", "兴趣小组人数扇形"],
            route=["看标题", "看图例", "读数量", "比大小", "说结论"],
            misconceptions=["只看图形好看不看刻度", "扇形图当条形图比长短"],
            visuals=["三种图对照"],
        ),
        _point(
            topic_id="median_mode_range",
            name="中位数、众数与极差",
            grade_band=b,
            grade="六年级至七年级",
            chapter="数据的分析",
            section="中位数、众数、极差",
            human="平均数会被极端值拉偏；中位数看「排在中间」的数；众数看「出现最多」的数；极差看最大最小差多少。",
            why="描述一组数据时，只记平均数往往不够。",
            terms={
                "中位数": "把数据按大小排好后，处在正中间的数。",
                "众数": "出现次数最多的数。",
                "极差": "最大值减最小值。",
            },
            formal="中位数、众数是描述数据集中趋势的统计量；极差描述离散程度的一种简单量。",
            prerequisites=["average", "data_collection_chart", "number_comparison"],
            next_topics=["data_analysis", "data_collection_description"],
            examples=["五次考试分数找中位数", "最受欢迎鞋码是众数"],
            route=["排序", "找中间", "数次数", "最大减最小", "和平均数对比"],
            misconceptions=["没排序就找中位数", "以为众数一定唯一"],
        ),
        _point(
            topic_id="angle_measure",
            name="角的度量",
            grade_band=p,
            grade="四年级上册",
            chapter="角的度量",
            section="角度与量角器",
            human="角是从一点出发的两条射线张开的大小；用量角器可以量出张开多少度。",
            why="三角形内角、平行线、旋转都要用「角有多大」。",
            terms={
                "度": "量角大小的单位，记作 °。",
                "直角": "正好 90° 的角。",
                "平角": "180°，看起来像一条直线。",
                "周角": "360°，转一整圈。",
            },
            formal="角的度量单位是度，1 周角=360°，1 平角=180°，1 直角=90°。",
            prerequisites=["line_angle_basic"],
            next_topics=["triangle_basic", "parallel_lines", "rotation"],
            examples=["课桌角大约是直角", "打开的书本夹角"],
            route=["顶点", "两条边", "张开大小", "用量角器", "读度数"],
            visuals=["量角器", "活动角"],
        ),
        _point(
            topic_id="parallel_perpendicular_primary",
            name="平行与垂直（小学）",
            grade_band=p,
            grade="四年级上册",
            chapter="平行四边形和梯形",
            section="平行线与垂线",
            human="同一平面内，永不相交的两条直线互相平行；相交成直角的两条直线互相垂直。",
            why="长方形、平行四边形、坐标系都建立在平行与垂直上。",
            terms={
                "平行": "同一平面内不相交，像铁轨。",
                "垂直": "相交成 90°。",
                "垂足": "两条线垂直时的交点。",
            },
            formal="在同一平面内不相交的两条直线互相平行；夹角为直角的两条直线互相垂直。",
            prerequisites=["line_angle_basic", "angle_measure"],
            next_topics=["parallelogram", "coordinate_plane", "parallel_lines"],
            examples=["本子的横线", "墙壁与地面"],
            route=["同一平面", "是否相交", "是否成直角", "画记号"],
            misconceptions=["看着「斜」就不是平行", "垂直必须横平竖直才算"],
        ),
        _point(
            topic_id="translation_rotation_flip",
            name="平移、旋转与轴对称",
            grade_band=p,
            grade="二年级至五年级",
            chapter="图形的运动",
            section="平移旋转轴对称",
            human="平移是整体滑动不转身；旋转是绕一个点转；轴对称是像照镜子一样对折能重合。",
            why="全等、相似、函数图像变换都从「图形怎么动」开始。",
            terms={
                "平移": "方向和距离一定，形状方向不变地移动。",
                "旋转": "绕定点转动一定角度。",
                "轴对称": "沿一条直线对折后两边重合。",
            },
            formal="平移、旋转、轴对称是小学阶段基本的图形运动。",
            prerequisites=["geometric_figures_intro", "rectangle_square_features"],
            next_topics=["axis_symmetry", "rotation", "congruent_triangles"],
            examples=["电梯门平移", "钟面指针旋转", "蝴蝶翅膀对称"],
            route=["看怎么动", "有没有翻转", "对应点", "对应角"],
            visuals=["描点移动", "对折纸"],
        ),
        _point(
            topic_id="area_triangle_trapezoid",
            name="三角形与梯形的面积",
            grade_band=p,
            grade="五年级上册",
            chapter="多边形的面积",
            section="三角形、梯形面积",
            human="三角形面积可以想成「同样底高的平行四边形的一半」；梯形可以想成上下底平均后再乘高。",
            why="后面圆、组合图形、以及用面积理解乘法公式都会用到。",
            terms={
                "底": "当作底边的那条边。",
                "高": "从对角顶点到这条底边的垂直距离。",
                "梯形": "只有一组对边平行的四边形。",
            },
            formal="三角形面积 = 底×高÷2；梯形面积 = (上底+下底)×高÷2。",
            prerequisites=["area", "parallelogram", "parallel_perpendicular_primary"],
            next_topics=["primary_circle_features", "volume"],
            formulas=["S=ah/2", "S=(a+b)h/2"],
            examples=["三角形花坛占地", "梯形田埂"],
            route=["找底和高", "为什么除以 2", "拼补图形", "套公式"],
            misconceptions=["高不垂直也乱乘", "梯形只用一个底"],
            worked_examples=[
                _worked(
                    "三角形面积为什么除以 2",
                    "底 6、高 4 的三角形面积怎么想？",
                    [
                        "先想一个底 6、高 4 的平行四边形，面积 6×4=24。",
                        "对角线把它分成两个一样的三角形。",
                        "所以每个三角形是 24÷2=12。",
                        "公式 ah/2 就是这个意思。",
                    ],
                    "能说出「除以 2」来自两个全等三角形，不是硬背。",
                )
            ],
        ),
        _point(
            topic_id="circle_circumference_area",
            name="圆的周长与面积",
            grade_band=p,
            grade="六年级上册",
            chapter="圆",
            section="圆周长与圆面积",
            human="圆周长是绕圆一圈的长度；圆面积是圆面铺了多大。它们都和半径、圆周率有关。",
            why="扇形、圆柱、圆锥和很多实际测量都建立在圆上。",
            terms={
                "半径": "圆心到圆上任意一点的线段长。",
                "直径": "穿过圆心、两端在圆上的线段，是半径的 2 倍。",
                "圆周率": "任何圆的周长与直径的比，约是 3.14，记作 π。",
            },
            formal="C=2πr=πd；S=πr²。",
            prerequisites=["primary_circle_features", "area", "decimal_operations"],
            next_topics=["volume", "circle", "trigonometric_ratios"],
            formulas=["C=2πr", "S=πr²"],
            examples=["圆形花坛一圈多长", "圆桌面有多大"],
            route=["半径直径", "π 是比", "周长", "面积", "别混"],
            misconceptions=["周长面积公式套反", "半径直径混用"],
        ),
        _point(
            topic_id="cuboid_cylinder_volume",
            name="长方体与圆柱的体积",
            grade_band=p,
            grade="五年级下册至六年级",
            chapter="长方体和圆柱",
            section="体积与容积",
            human="体积是物体占空间多大；长方体可想成「底面积×高」；圆柱也是「圆底面积×高」。",
            why="容积、密度和后面立体几何都要用体积直觉。",
            terms={
                "体积": "物体所占空间的大小。",
                "容积": "容器最多能装多少（从里面量）。",
                "底面积": "底面那一层的面积。",
            },
            formal="长方体体积 V=abh；圆柱体积 V=πr²h。",
            prerequisites=["volume", "circle_circumference_area", "area"],
            next_topics=["solid_geometry_spatial_relations"],
            formulas=["V=abh", "V=Sh", "V=πr²h"],
            examples=["纸箱能装多少", "水杯大约装多少毫升"],
            route=["占空间", "一层层累起来", "底面积", "乘高"],
            misconceptions=["体积容积单位混用", "圆柱当成长方体乱套"],
        ),
        _point(
            topic_id="word_problem_diagram",
            name="线段图与应用题",
            grade_band=p,
            grade="三年级至六年级",
            chapter="数学广角 / 实际问题",
            section="用线段图表征数量关系",
            human="线段图是把条件和问题画成线段长短，让「多多少、少多少、几倍」看得见。",
            why="方程应用、行程工程问题，先画清楚比硬套公式重要。",
            terms={
                "线段图": "用线段表示数量关系的图。",
                "单位量": "当作 1 份的那个量。",
                "问题": "题目要求的未知结果。",
            },
            formal="线段图是小学阶段表征应用题数量关系的常用工具。",
            prerequisites=["quantity_relationship", "integer_addition_subtraction", "fraction"],
            next_topics=[
                "equation_applications_primary",
                "rate_speed_distance",
                "primary_equation",
            ],
            examples=["甲比乙多 3 个", "乙是甲的 2 倍少 1"],
            route=["读题", "谁和谁比", "画线段", "标已知", "找所求"],
            misconceptions=["不标单位就画", "倍比和差比混在一根线上乱标"],
            visuals=["线段图模板"],
        ),
        _point(
            topic_id="interest_simple",
            name="利息与百分数应用",
            grade_band=p,
            grade="六年级",
            chapter="百分数的应用",
            section="利息、折扣、税率初步",
            human="利息可以想成：本金按一定百分率，过一段时间「多出来」的钱。",
            why="把百分数从「会算」推进到「会解释生活里的涨跌」。",
            terms={
                "本金": "一开始存进去或借出的钱。",
                "利率": "利息占本金的百分率。",
                "利息": "额外得到或支付的钱。",
            },
            formal="单利利息 ≈ 本金 × 利率 × 时间（小学阶段的简化模型）。",
            prerequisites=["percent", "decimal_operations", "money_calculation"],
            next_topics=["linear_function", "rate_speed_distance"],
            formulas=["利息=本金×利率×时间"],
            examples=["存 1000 元，年利率 2%"],
            route=["本金", "百分之几", "时间", "多出来的钱", "本息和"],
            misconceptions=["利率和时间单位不匹配", "百分号当小数乱移"],
        ),
        # —— 初中：代数与函数加厚 ——
        _point(
            topic_id="number_line",
            name="数轴",
            grade_band=j,
            grade="七年级上册",
            chapter="有理数",
            section="数轴",
            human="数轴是画成一条线的「数的家」：原点、正方向、单位长度定好后，每个有理数都有一个点。",
            why="绝对值、不等式、函数图像都建立在「数可以对应点」上。",
            terms={
                "原点": "表示 0 的那一点。",
                "正方向": "通常向右，表示越来越大的方向。",
                "单位长度": "从 0 到 1 的那段长度。",
            },
            formal="规定了原点、正方向和单位长度的直线叫做数轴。",
            prerequisites=["rational_numbers", "negative_number_intro"],
            next_topics=["absolute_value", "inequalities", "coordinate_plane"],
            examples=["温度计像竖着的数轴", "向东为正向西为负"],
            route=["画线", "定 0", "定方向", "定 1 的长度", "定点"],
            misconceptions=["负数方向画反", "单位长度忽大忽小"],
        ),
        _point(
            topic_id="opposite_numbers",
            name="相反数",
            grade_band=j,
            grade="七年级上册",
            chapter="有理数",
            section="相反数",
            human="相反数是「离 0 一样远，但在数轴两边」的两个数；把符号对调就得到相反数。",
            why="减法要化成加法、解方程移项，都会用到相反数。",
            terms={
                "相反数": "只有符号不同的两个数，如 3 与 -3。",
                "互为相反数": "彼此是对方的相反数。",
            },
            formal="只有符号不同的两个数叫做互为相反数；0 的相反数是 0。",
            prerequisites=["number_line", "rational_numbers"],
            next_topics=["absolute_value", "rational_numbers"],
            examples=["前进 5 与后退 5", "盈利 8 与亏损 8"],
            route=["数轴对称", "符号", "0 的特殊", "运算里变号"],
        ),
        _point(
            topic_id="adding_subtracting_rational",
            name="有理数加减法",
            grade_band=j,
            grade="七年级上册",
            chapter="有理数",
            section="有理数的加减",
            human="有理数加减可以想成在数轴上向右（加正）或向左（加负）移动；减法等于加上相反数。",
            why="整式、方程、函数里的符号运算都从这里稳住。",
            terms={
                "同号": "两个数符号相同。",
                "异号": "两个数符号不同。",
                "绝对值大的数": "离 0 更远的那个，决定和的符号（异号时）。",
            },
            formal="a−b=a+(−b)；同号相加取相同符号并加绝对值，异号相加取绝对值较大者的符号并减绝对值。",
            prerequisites=["absolute_value", "opposite_numbers", "number_line"],
            next_topics=["algebraic_expression", "linear_equation_one_variable"],
            examples=["温度从 -3℃ 升高 5℃", "收支相抵"],
            route=["化成加法", "看同号异号", "算绝对值", "定符号"],
            misconceptions=["只减绝对值忘了符号", "减去负数时变号错"],
        ),
        _point(
            topic_id="multiplying_dividing_rational",
            name="有理数乘除法",
            grade_band=j,
            grade="七年级上册",
            chapter="有理数",
            section="有理数的乘除",
            human="乘除先定符号：同号得正、异号得负；再把绝对值按整数乘除算。",
            why="整式乘法、科学记数法、负斜率函数都要用。",
            terms={
                "积的符号": "由因数符号决定：同正异负。",
                "倒数": "乘积为 1 的两个数互为倒数。",
            },
            formal="负负得正、异号得负；a÷b=a×(1/b)（b≠0）。",
            prerequisites=["adding_subtracting_rational", "fraction_operations"],
            next_topics=["power_scientific_notation", "algebraic_expression"],
            examples=["连续两次转向", "平均分配债务"],
            route=["先符号", "后绝对值", "除法变乘倒数", "0 不能做除数"],
        ),
        _point(
            topic_id="scientific_notation",
            name="科学记数法",
            grade_band=j,
            grade="七年级上册",
            chapter="整式的加减",
            section="科学记数法",
            human=(
                "科学记数法是把很大或很小的数写成 a×10ⁿ 的样子，"
                "其中 a 在 1 到 10 之间，方便比大小和读写。"
            ),
            why="天文、微粒、计算器显示都会用这种写法。",
            terms={
                "科学记数法": "a×10ⁿ 的记法，1≤|a|<10，n 为整数。",
                "数量级": "大致由 10 的指数反映「有多大/多小」。",
            },
            formal="任一非零数可写成 a×10ⁿ（1≤|a|<10，n∈Z）的形式，称为科学记数法。",
            prerequisites=["power_scientific_notation", "decimal", "multiplying_dividing_rational"],
            next_topics=["real_numbers", "linear_function"],
            formulas=["3.0×10^8", "2.5×10^{-3}"],
            examples=["光速约 3×10⁸ m/s", "0.0025=2.5×10⁻³"],
            route=["移动小数点", "数位数得指数", "写 a", "检查范围"],
        ),
        _point(
            topic_id="formula_square_difference",
            name="平方差公式",
            grade_band=j,
            grade="八年级上册",
            chapter="整式的乘法",
            section="平方差公式",
            human="两数和乘两数差，结果等于它们的平方差：前面两项交叉的中间项会消掉。",
            why="因式分解、心算、后面的公式变形会反复用。",
            terms={
                "平方差": "两个数的平方相减。",
                "公式": "可以反复套用的标准写法。",
            },
            formal="(a+b)(a−b)=a²−b²。",
            prerequisites=["polynomial_multiplication", "distributive_property"],
            next_topics=["factorization", "formula_perfect_square"],
            formulas=["(a+b)(a-b)=a^2-b^2"],
            examples=["99×101", "(x+3)(x-3)"],
            route=["认出和与差", "交叉项抵消", "剩平方减平方", "验算展开"],
            misconceptions=["写成 a²+b²", "符号弄反"],
            worked_examples=[
                _worked(
                    "用平方差算 98×102",
                    "怎样心算 98×102？",
                    [
                        "看成 (100−2)(100+2)。",
                        "套公式得 100²−2²。",
                        "10000−4=9996。",
                        "说明公式在「少算中间交叉项」。",
                    ],
                    "能说明为什么中间项消失。",
                )
            ],
        ),
        _point(
            topic_id="formula_perfect_square",
            name="完全平方公式",
            grade_band=j,
            grade="八年级上册",
            chapter="整式的乘法",
            section="完全平方公式",
            human="两数和（或差）的平方，不只是两项平方相加，还要加上（或减去）它们乘积的 2 倍。",
            why="配方法、二次函数顶点式都靠完全平方。",
            terms={
                "完全平方式": "能写成某个式子平方的式子。",
                "中间项": "2ab 这一项，最容易漏。",
            },
            formal="(a±b)²=a²±2ab+b²。",
            prerequisites=["polynomial_multiplication", "formula_square_difference"],
            next_topics=["factorization", "quadratic_equation", "quadratic_function"],
            formulas=["(a+b)^2=a^2+2ab+b^2"],
            examples=["(x+1)²", "边长 a+b 的正方形面积"],
            route=["画正方形拆块", "两块矩形是 2ab", "不要漏中间", "展开验算"],
            misconceptions=["(a+b)²=a²+b²", "符号只改一项"],
            visuals=["正方形面积拆分"],
        ),
        _point(
            topic_id="linear_inequality_solving",
            name="一元一次不等式的解法",
            grade_band=j,
            grade="七年级下册",
            chapter="不等式与不等式组",
            section="解一元一次不等式",
            human="解不等式很像解方程，但有一条关键不同：两边同乘或同除一个负数时，不等号要反向。",
            why="取值范围、可行域、函数定义域都会用不等式语言。",
            terms={
                "解集": "所有使不等式成立的未知数取值的集合。",
                "不等号变向": "乘除负数时，大于变小于、小于变大于。",
            },
            formal="解一元一次不等式的步骤与方程类似，移项变号；乘除负数时不等号改变方向。",
            prerequisites=["inequalities", "linear_equation_one_variable", "number_line"],
            next_topics=["inequality_systems", "function_intro"],
            examples=["2x+1>5", "−3x≥6"],
            route=["化简", "移项", "系数化为 1", "注意负数", "数轴表示"],
            misconceptions=["乘负数忘变向", "解集不会在数轴上表示"],
        ),
        _point(
            topic_id="systems_substitution_addition",
            name="代入法与加减法解方程组",
            grade_band=j,
            grade="七年级下册",
            chapter="二元一次方程组",
            section="代入法、加减法",
            human="代入法是从一个方程解出一个未知数，塞进另一个方程；加减法是让某个未知数系数相反再相加消掉。",
            why="这是「消元」思想：把两个未知变成一个未知。",
            terms={
                "消元": "想办法去掉一个未知数。",
                "代入": "用等于的式子去替换。",
                "加减消元": "两式相加或相减消去一项。",
            },
            formal="解二元一次方程组常用代入消元法与加减消元法。",
            prerequisites=["linear_equation_systems", "linear_equation_one_variable"],
            next_topics=["linear_equation_two_variables", "linear_function"],
            examples=["鸡兔同笼列方程组", "两商品价格问题"],
            route=["选方法", "消元", "解一元", "回代", "检验"],
        ),
        _point(
            topic_id="function_concept_junior",
            name="变量与函数（再认）",
            grade_band=j,
            grade="八年级下册",
            chapter="一次函数",
            section="变量与函数",
            human="在一个变化过程里，有的量会变叫变量；如果一个量确定后另一个量跟着唯一确定，就说后者是前者的函数。",
            why="一次、反比例、二次函数都是这一句话的不同长相。",
            terms={
                "变量": "可以取不同值的量。",
                "常量": "在讨论过程中不变的量。",
                "自变量": "主动变化、当作输入的量。",
                "函数值": "对应出来的输出。",
            },
            formal=(
                "一般地，在一个变化过程中，如果有两个变量 x 与 y，"
                "对于 x 的每一个确定的值，y 都有唯一确定的值与它对应，"
                "那么就说 y 是 x 的函数。"
            ),
            prerequisites=["function_intro", "quantity_relationship", "coordinate_plane"],
            next_topics=[
                "linear_function",
                "function_graph_reading",
                "inverse_proportion_function",
            ],
            examples=["出租车费随里程变", "温度随时间变"],
            route=["找两个量", "谁随谁变", "是否唯一对应", "表格图像表达式"],
            misconceptions=["有两个字母就是函数", "一个 x 对应两个 y 仍叫函数"],
        ),
        _point(
            topic_id="slope_intercept_meaning",
            name="一次函数的斜率与截距",
            grade_band=j,
            grade="八年级下册",
            chapter="一次函数",
            section="k 与 b 的意义",
            human="在 y=kx+b 里，k 描述「斜得多厉害、向哪边斜」，b 描述直线与 y 轴交在哪里。",
            why="读图、写解析式、比较变化快慢都靠 k、b。",
            terms={
                "斜率": "这里先理解为 k，反映倾斜程度与正负方向。",
                "截距": "与坐标轴交点的坐标；常说的纵截距是 b。",
            },
            formal="一次函数 y=kx+b（k≠0）中，k 为斜率，b 为直线在 y 轴上的截距。",
            prerequisites=["linear_function", "function_graph_reading", "ratio"],
            next_topics=["quadratic_function", "inverse_proportion_function"],
            formulas=["y=kx+b"],
            examples=["y=2x+1 比 y=x+1 更陡", "b 改变则上下平移"],
            route=["k>0 上升", "k<0 下降", "|k| 大更陡", "b 是纵截距"],
            misconceptions=["k 只表示角度数字", "b 与 x 轴截距混淆"],
        ),
        _point(
            topic_id="quadratic_formula",
            name="求根公式与配方法",
            grade_band=j,
            grade="九年级上册",
            chapter="一元二次方程",
            section="配方法与公式法",
            human="配方法是把方程凑成完全平方式再开方；求根公式是把配方过程固化成可直接套的式子。",
            why="不是每道方程都能因式分解，公式法保证「能解就解出来」。",
            terms={
                "配方法": "通过加减项把左边变成完全平方。",
                "求根公式": "ax²+bx+c=0（a≠0）的解的公式。",
                "判别式": "b²−4ac，用来判断有没有实数根。",
            },
            formal="x=[−b±√(b²−4ac)]/(2a)，其中 Δ=b²−4ac。",
            prerequisites=["quadratic_equation", "formula_perfect_square", "quadratic_radicals"],
            next_topics=["quadratic_function", "quadratic_function_high_school"],
            formulas=["x=[-b±sqrt(b^2-4ac)]/(2a)"],
            examples=["x²−5x+6=0", "x²+2x−2=0"],
            route=["化一般式", "算 Δ", "判断根", "代入公式", "检验"],
            misconceptions=["Δ 算错仍硬套", "分母 2a 漏写"],
        ),
        _point(
            topic_id="quadratic_vertex",
            name="二次函数的顶点与增减",
            grade_band=j,
            grade="九年级上册",
            chapter="二次函数",
            section="顶点式与图像",
            human="抛物线有最高点或最低点叫顶点；顶点把图像分成上升和下降两段。",
            why="最值问题、配方法、图像平移都落在顶点上。",
            terms={
                "顶点": "抛物线的最高或最低点。",
                "对称轴": "把抛物线分成对称两半的竖直线。",
                "开口方向": "由二次项系数正负决定向上或向下。",
            },
            formal="y=a(x−h)²+k 的顶点为 (h,k)；a>0 开口向上，a<0 开口向下。",
            prerequisites=[
                "quadratic_function",
                "formula_perfect_square",
                "function_graph_reading",
            ],
            next_topics=["quadratic_function_high_school", "derivative_intro"],
            formulas=["y=a(x-h)^2+k"],
            examples=["喷泉高度", "利润最大问题直觉"],
            route=["看 a 正负", "找顶点", "对称轴", "左右增减"],
        ),
        # —— 初中几何加厚 ——
        _point(
            topic_id="triangle_angle_sum",
            name="三角形内角和",
            grade_band=j,
            grade="八年级上册",
            chapter="三角形",
            section="内角和定理",
            human="任意三角形三个内角加起来都是 180°，像把三个角撕下来能拼成一个平角。",
            why="求角、证明平行、相似判定都会反复用。",
            terms={
                "内角": "三角形内部的角。",
                "外角": "一边与邻边延长线的夹角。",
            },
            formal="三角形三个内角的和等于 180°。",
            prerequisites=["triangle_basic", "angle_measure", "parallel_lines"],
            next_topics=["congruent_triangles", "similar_triangles", "pythagorean_theorem"],
            formulas=["∠A+∠B+∠C=180°"],
            examples=["已知两角求第三角", "等边三角形每个角 60°"],
            route=["撕角拼平角", "平行线证明思路", "用定理求角"],
            visuals=["撕纸拼角"],
        ),
        _point(
            topic_id="congruent_criteria",
            name="全等三角形判定",
            grade_band=j,
            grade="八年级上册",
            chapter="全等三角形",
            section="SSS、SAS、ASA、AAS、HL",
            human="全等是形状大小完全一样，能完全重合；判定是「满足哪些条件就能断定全等」，不用比所有边角。",
            why="几何证明里最常用的「桥」。",
            terms={
                "全等": "形状和大小都相同，对应边角相等。",
                "对应": "重合时落在一起的边或角。",
                "判定": "用来下结论的条件组合。",
            },
            formal="常用判定：SSS、SAS、ASA、AAS；直角三角形还有 HL。",
            prerequisites=["congruent_triangles", "triangle_basic", "geometric_proof_intro"],
            next_topics=["similar_triangles", "pythagorean_theorem"],
            examples=["桥架对称结构", "复制定理证明"],
            route=["找已知边角", "选判定", "写对应", "推对应相等"],
            misconceptions=["AAA 能判定全等", "对应乱写导致边角不配"],
        ),
        _point(
            topic_id="similar_ratio",
            name="相似比与相似三角形",
            grade_band=j,
            grade="九年级下册",
            chapter="相似",
            section="相似三角形",
            human="相似是形状一样、大小可以不同；对应边成比例，对应角相等。",
            why="测量无法直接量的高度、地图比例、三角函数的几何基础。",
            terms={
                "相似": "形状相同，大小未必相同。",
                "相似比": "对应边的比值。",
                "对应角": "位置对应的角，相似时相等。",
            },
            formal="对应角相等、对应边成比例的三角形叫做相似三角形。",
            prerequisites=["similar_triangles", "ratio", "congruent_criteria"],
            next_topics=["trigonometric_ratios", "proportion"],
            formulas=["a/a'=b/b'=c/c'=k"],
            examples=["影子测高", "放大图纸"],
            route=["找相等角", "找比例边", "写相似比", "求未知边"],
        ),
        _point(
            topic_id="pythagorean_applications",
            name="勾股定理的应用",
            grade_band=j,
            grade="八年级下册",
            chapter="勾股定理",
            section="应用",
            human="直角三角形里，两条直角边的平方和等于斜边的平方；可用来求边长或判断是否直角。",
            why="距离、导航、空间对角线的平面基础。",
            terms={
                "直角边": "夹直角的两条边。",
                "斜边": "直角的对边，最长。",
                "勾股数": "能构成直角三角形边长的正整数组合，如 3、4、5。",
            },
            formal="直角三角形两直角边 a、b 与斜边 c 满足 a²+b²=c²。",
            prerequisites=["pythagorean_theorem", "quadratic_radicals", "triangle_basic"],
            next_topics=["coordinate_plane", "trigonometric_ratios", "space_vectors"],
            formulas=["a^2+b^2=c^2"],
            examples=["梯子靠墙", "电视屏幕尺寸"],
            route=["确认直角", "谁是斜边", "代入", "取算术平方根"],
            misconceptions=["斜边代错", "开方丢单位"],
        ),
        _point(
            topic_id="circle_central_inscribed",
            name="圆心角与圆周角",
            grade_band=j,
            grade="九年级上册",
            chapter="圆",
            section="圆心角、圆周角",
            human="圆心角的顶点在圆心；圆周角的顶点在圆上。同弧所对的圆周角是圆心角的一半。",
            why="圆的很多证明和计算都绕着「角与弧的对应」。",
            terms={
                "圆心角": "顶点在圆心的角。",
                "圆周角": "顶点在圆周、两边和圆相交的角。",
                "弧": "圆上两点之间的部分。",
            },
            formal="同弧或等弧所对的圆周角等于它所对圆心角的一半。",
            prerequisites=["circle", "angle_measure", "triangle_angle_sum"],
            next_topics=["trigonometric_ratios"],
            examples=["看表盘扇形", "拱桥圆弧"],
            route=["找弧", "找圆心角", "找圆周角", "用一半关系"],
        ),
        _point(
            topic_id="view_of_solids",
            name="三视图初步",
            grade_band=j,
            grade="七年级至九年级",
            chapter="丰富的图形世界 / 投影与视图",
            section="主视图、左视图、俯视图",
            human="三视图是从正面、左面、上面看立体得到的平面图形，用来把空间形状说清楚。",
            why="读图纸、理解立体几何对象的第一步。",
            terms={
                "主视图": "从正面看。",
                "左视图": "从左面看。",
                "俯视图": "从上面看。",
            },
            formal="物体的三视图是正投影下从三个方向得到的投影图。",
            prerequisites=["geometric_figures_intro", "volume"],
            next_topics=["solid_geometry_spatial_relations"],
            examples=["积木堆的三视图", "纸箱"],
            route=["选定方向", "看轮廓", "长对正", "高平齐", "宽相等"],
            misconceptions=["把斜线当看得见的棱乱画", "视图方向搞反"],
        ),
        _point(
            topic_id="probability_classical",
            name="古典概型直觉",
            grade_band=j,
            grade="九年级上册",
            chapter="概率初步",
            section="等可能情形下的概率",
            human="如果每个基本结果机会一样，事件概率就是「符合条件的结果数 ÷ 全部结果数」。",
            why="列表树状图之后，用分数语言描述可能性。",
            terms={
                "基本结果": "一次试验最细的可能结果。",
                "等可能": "每个基本结果机会相同。",
                "概率": "可能性大小的数，常在 0 到 1 之间。",
            },
            formal="古典概型中，P(A)=m/n，其中 n 为等可能基本结果总数，m 为事件 A 包含的结果数。",
            prerequisites=["probability", "probability_tree_listing", "fraction"],
            next_topics=["probability_high_school", "random_variables"],
            formulas=["P=m/n"],
            examples=["掷均匀骰子得偶数", "袋中摸球"],
            route=["确认等可能", "列全结果", "数符合的", "写成分数", "约分"],
            misconceptions=["没列全就除", "把「感觉可能」当等可能"],
        ),
        _point(
            topic_id="sampling_bias",
            name="抽样与偏差直觉",
            grade_band=j,
            grade="八年级下册至九年级",
            chapter="数据分析",
            section="抽样调查",
            human="抽样是只查一部分来了解全体；样本要有代表性，否则结论会偏。",
            why="媒体数据和统计题都要会问：这样本代表谁？",
            terms={
                "总体": "要了解的全体。",
                "样本": "实际调查的一部分。",
                "偏差": "样本系统性偏向某类对象。",
            },
            formal="用样本估计总体时，抽样方式影响估计的可靠性。",
            prerequisites=["data_analysis", "data_collection_description", "average"],
            next_topics=["normal_distribution", "random_variables"],
            examples=["只在篮球社问平均身高", "网上自愿填问卷"],
            route=["谁是总体", "怎么抽", "会不会偏", "结论能推广吗"],
        ),
        _point(
            topic_id="set_language_junior",
            name="集合语言入门",
            grade_band=b,
            grade="九年级至高一衔接",
            chapter="预备知识",
            section="集合的描述",
            human="集合是把一些对象打包看成一个整体；用「属于」说明某个对象在不在包里。",
            why="函数定义域、不等式解集、概率样本空间都会用集合说话。",
            terms={
                "集合": "确定的一些对象组成的整体。",
                "元素": "集合里的对象。",
                "属于": "元素在集合中，记作 ∈。",
            },
            formal="集合由元素构成；元素与集合的关系是属于或不属于。",
            prerequisites=["inequalities", "function_concept_junior"],
            next_topics=["set_concept", "function_properties_high_school"],
            examples=["班级里所有女生", "方程的解的集合"],
            route=["说清对象", "不重复", "确定准则", "用符号写"],
            misconceptions=["含糊对象也能成集合", "同一元素写两次"],
        ),
        _point(
            topic_id="absolute_value_equations",
            name="绝对值方程初步",
            grade_band=j,
            grade="七年级至八年级",
            chapter="有理数 / 绝对值",
            section="简单绝对值方程",
            human="绝对值表示到 0 的距离；含绝对值的方程常要按「里面是正是负」分成两边讨论。",
            why="为二次函数、距离公式和解更复杂的方程做准备。",
            terms={
                "绝对值方程": "未知数出现在绝对值号里的方程。",
                "零点分段": "让绝对值里面为 0 的点，用来分情况。",
            },
            formal="|x|=a（a>0）的解是 x=a 或 x=−a。",
            prerequisites=["absolute_value", "linear_equation_one_variable", "number_line"],
            next_topics=["inequalities", "quadratic_equation"],
            examples=["|x|=3", "|x−1|=2"],
            route=["绝对值意义", "距离", "两种可能", "检验"],
        ),
        _point(
            topic_id="polynomial_degree_terms",
            name="整式的次数与项",
            grade_band=j,
            grade="七年级上册",
            chapter="整式的加减",
            section="项、系数、次数",
            human="整式由一项一项加起来；每一项有系数和次数，整式的次数看次数最高的那一项。",
            why="合并同类项、多项式乘法都要先认清「项」。",
            terms={
                "项": "用加号连接的每一块（减号可看成加负数）。",
                "系数": "项里头的数字因数。",
                "次数": "一项里字母指数的和；多项式取最高的。",
            },
            formal="整式是数或含字母的积以及它们的和；多项式的次数是次数最高的项的次数。",
            prerequisites=["algebraic_expression", "like_terms"],
            next_topics=["polynomial_multiplication", "factorization"],
            examples=["3x²−2x+1 是二次三项式"],
            route=["拆项", "看系数", "看字母指数", "定次数"],
        ),
        _point(
            topic_id="factor_common_factor",
            name="提公因式法",
            grade_band=j,
            grade="八年级上册",
            chapter="因式分解",
            section="提公因式",
            human="提公因式是把每一项都有的公共部分提出来，写成乘法形式，方便约分或继续分解。",
            why="因式分解最基本的一招，后面公式法经常先提公因式。",
            terms={
                "公因式": "每一项都含有的公共因式。",
                "因式分解": "把和差形式写成积的形式。",
            },
            formal="ab+ac=a(b+c)。",
            prerequisites=["factorization", "distributive_property", "polynomial_degree_terms"],
            next_topics=["formula_square_difference", "rational_expression"],
            examples=["2x+4=2(x+2)", "x²+x=x(x+1)"],
            route=["找公共的", "提出来", "括号里剩什么", "展开检验"],
        ),
        _point(
            topic_id="rational_equation_intro",
            name="分式方程入门",
            grade_band=j,
            grade="八年级上册",
            chapter="分式",
            section="分式方程",
            human=(
                "分式方程是分母里含未知数的方程；要先找公分母去分母，"
                "最后必须检验，因为可能使分母为 0。"
            ),
            why="工程问题、浓度问题常列出分式方程。",
            terms={
                "分式方程": "分母含未知数的方程。",
                "增根": "去分母后多出来、使原分母为 0 的根。",
            },
            formal="解分式方程需去分母转化为整式方程，并检验使分母不为 0。",
            prerequisites=[
                "rational_expression",
                "linear_equation_one_variable",
                "fraction_operations",
            ],
            next_topics=["linear_equation_applications"],
            examples=["1/x=2", "行程中速度关系"],
            route=["找公分母", "去分母", "解整式方程", "检验分母"],
            misconceptions=["不检验增根", "公分母漏因式"],
        ),
        _point(
            topic_id="inverse_proportion_graph",
            name="反比例函数图像",
            grade_band=j,
            grade="九年级下册",
            chapter="反比例函数",
            section="图像与性质",
            human=(
                "反比例函数 y=k/x（k≠0）的图像是双曲线，两支分别在对角象限，"
                "越靠近坐标轴越贴近但不相交。"
            ),
            why="理解「积一定」时的变化，并和一次函数对比。",
            terms={
                "双曲线": "反比例函数图像的形状名称。",
                "象限": "坐标平面被轴分成的四个区域。",
            },
            formal="函数 y=k/x（k≠0）叫做反比例函数。",
            prerequisites=["inverse_proportion_function", "function_graph_reading", "proportion"],
            next_topics=["function_properties_high_school"],
            formulas=["y=k/x"],
            examples=["矩形面积一定时长与宽", "行程中速度与时间（路程一定）"],
            route=["k 正负定象限", "列表描点", "看增减", "不与轴相交"],
        ),
        _point(
            topic_id="trig_ratio_right_triangle",
            name="锐角三角函数定义",
            grade_band=j,
            grade="九年级下册",
            chapter="锐角三角函数",
            section="正弦余弦正切",
            human="在直角三角形里，一个锐角的对边、邻边与斜边的比值是固定的，分别叫正弦、余弦、正切。",
            why="测高、测距、物理分解力的几何语言。",
            terms={
                "对边": "不挨着这个角的那条边。",
                "邻边": "夹这个角的直角边。",
                "正弦": "对边比斜边。",
                "余弦": "邻边比斜边。",
                "正切": "对边比邻边。",
            },
            formal="sinθ=对边/斜边，cosθ=邻边/斜边，tanθ=对边/邻边。",
            prerequisites=["trigonometric_ratios", "pythagorean_applications", "similar_ratio"],
            next_topics=["trigonometric_functions"],
            formulas=["sin, cos, tan"],
            examples=["仰角测楼高", "坡度"],
            route=["标直角", "定锐角", "找对边邻边斜边", "写比值", "用表或计算器"],
            misconceptions=["对边邻边搞反", "不是直角三角形硬套定义"],
        ),
    ]
