from __future__ import annotations

from collections.abc import Iterable, Mapping

from math_learning_graph.depth import with_deep_scaffold
from math_learning_graph.models import (
    GradeBand,
    KnowledgePoint,
    PracticeTask,
    TextbookPosition,
    WorkedExample,
)

CURRICULUM = "人教A版普通高中数学"


def _pos(grade: str, chapter: str, section: str) -> TextbookPosition:
    return TextbookPosition(curriculum=CURRICULUM, grade=grade, chapter=chapter, section=section)


def _worked(name: str, symbol_step: str, problem: str) -> WorkedExample:
    return WorkedExample(
        title=f"先读懂{name}",
        problem=problem,
        steps=[
            symbol_step,
            "再说这一步要处理的关系，不急着套公式。",
            f"最后把题目语言翻译成{name}的数学表达，并检查每个量是什么意思。",
        ],
        answer_check="能解释每个符号或关键词，才继续计算。",
    )


def _task(level: str, prompt: str, goal: str) -> PracticeTask:
    return PracticeTask(level=level, prompt=prompt, goal=goal)


def _point(
    *,
    topic_id: str,
    name: str,
    grade: str,
    chapter: str,
    section: str,
    human: str,
    why: str,
    terms: Mapping[str, str],
    prerequisites: Iterable[str] = (),
    next_topics: Iterable[str] = (),
    formulas: Iterable[str] = (),
) -> KnowledgePoint:
    point = KnowledgePoint(
        id=topic_id,
        name=name,
        grade_band=GradeBand.SENIOR,
        textbook_positions=[_pos(grade, chapter, section)],
        human_explanation=human,
        life_examples=[f"用{name}描述一个具体数量或图形关系"],
        why_needed=why,
        formal_definition=human,
        term_explanations=dict(terms),
        misconceptions=[f"只背{name}的课本说法，却说不出每个词在题里指什么。"],
        prerequisite_ids=list(prerequisites),
        next_ids=list(next_topics),
        formulas=list(formulas),
        visualization_methods=["先画关系图", "再列表或画坐标图", "最后写符号"],
        ai_teaching_hints=["先解释词，再解释关系；不要用高中术语解释高中术语。"],
        exercise_types=["解释关键词", "课本例题拆步", "换情境判断"],
        school_route=[grade, chapter, section],
        understanding_route=["解释词", "找对象", "找关系", "写符号", "检验含义"],
        conceptual_layers=[
            f"先把词说清楚：{name}不是一个要背的标题，先问它在题里指哪些对象。",
            f"再看关系：{human}",
            "最后才写符号；每写一个字母、括号或图像，都要能说出它代表什么。",
        ],
        worked_examples=[
            _worked(
                name,
                f"先解释这个词：{next(iter(terms))}，意思是{next(iter(terms.values()))}",
                f"给一个关于{name}的课本例题，先不计算，只圈出关键词和符号。",
            )
        ],
        practice_ladder=[
            _task("看懂", f"用自己的话解释{name}里的三个关键词。", "确认没有跳过术语。"),
            _task("会做", f"拆一题{name}课本例题，每一步写出依据。", "把概念和步骤连起来。"),
            _task("迁移", f"换一个情境判断还能不能用{name}。", "防止只会熟题。"),
        ],
        reflection_questions=[
            "这道题里每个新词是什么意思？",
            "我写的每个符号分别代表什么对象？",
            "如果换一个表示方式，关系还一样吗？",
        ],
    )
    return with_deep_scaffold(point)


def load_high_school_knowledge_points() -> list[KnowledgePoint]:
    return [
        _point(
            topic_id="set_concept",
            name="集合",
            grade="高中必修第一册",
            chapter="集合与常用逻辑用语",
            section="集合的概念",
            human="集合就是把满足同一条件的对象放在一起讨论。",
            why="高中函数、概率和不等式都需要先说清楚对象属于哪个范围。",
            terms={
                "元素": "集合里的每一个对象。",
                "属于": "某个对象在这个集合里。",
                "集合": "一批对象组成的整体。",
            },
            prerequisites=["number_recognition"],
            next_topics=["function_properties_high_school", "inequality_high_school"],
            formulas=["x in A"],
        ),
        _point(
            topic_id="logic_conditions",
            name="充分条件与必要条件",
            grade="高中必修第一册",
            chapter="集合与常用逻辑用语",
            section="充分条件与必要条件",
            human="充分条件是有它就够推出结论，必要条件是没有它结论就不可能成立。",
            why="证明题和判断命题时，必须分清谁推出谁。",
            terms={
                "命题": "能判断真假的一句数学话。",
                "推出": "前一句成立时后一句也成立。",
                "条件": "让结论成立所依赖的信息。",
            },
            prerequisites=["geometric_proof_intro"],
            next_topics=["derivative_applications"],
        ),
        _point(
            topic_id="inequality_high_school",
            name="高中不等式",
            grade="高中必修第一册",
            chapter="一元二次函数、方程和不等式",
            section="不等式",
            human="不等式是在找一批让大小关系成立的数，而不是只找一个答案。",
            why="函数定义域、最值和参数范围都要用不等式描述。",
            terms={
                "范围": "一批可能的数。",
                "解集": "所有能让不等式成立的数。",
                "边界": "范围开始或结束的位置。",
            },
            prerequisites=["inequalities"],
            next_topics=["quadratic_function_high_school"],
        ),
        _point(
            topic_id="quadratic_function_high_school",
            name="二次函数高中视角",
            grade="高中必修第一册",
            chapter="一元二次函数、方程和不等式",
            section="二次函数与一元二次方程、不等式",
            human="二次函数用抛物线描述含平方的变化关系。",
            why="它把方程的根、不等式的范围和图像位置连在一起。",
            terms={
                "抛物线": "二次函数图像的弯曲曲线。",
                "顶点": "抛物线最高或最低的位置。",
                "零点": "图像和x轴相交的位置。",
            },
            prerequisites=["quadratic_function"],
            next_topics=["function_properties_high_school"],
            formulas=["y = ax^2 + bx + c"],
        ),
        _point(
            topic_id="function_properties_high_school",
            name="函数性质",
            grade="高中必修第一册",
            chapter="函数的概念与性质",
            section="函数的单调性、奇偶性",
            human="函数性质是在描述输入变化时，输出整体上怎样变化。",
            why="研究函数图像、最值和导数前，要先会读函数的整体行为。",
            terms={
                "单调性": "输入变大时输出是跟着变大还是变小。",
                "奇偶性": "图像关于原点或y轴是否对称。",
                "定义域": "允许输入的所有值。",
            },
            prerequisites=["function_intro"],
            next_topics=["exponential_logarithmic_functions", "trigonometric_functions"],
        ),
        _point(
            topic_id="power_functions",
            name="幂函数",
            grade="高中必修第一册",
            chapter="函数的概念与性质",
            section="幂函数",
            human="幂函数是输入反复相乘形成的变化关系。",
            why="它是理解增长速度和函数图像形状的基本样本。",
            terms={
                "幂": "同一个数按次数相乘。",
                "指数": "说明相乘多少次或怎样取根。",
                "图像": "函数关系画在坐标系里的形状。",
            },
            prerequisites=["power_scientific_notation"],
            next_topics=["exponential_logarithmic_functions"],
            formulas=["y = x^a"],
        ),
        _point(
            topic_id="exponential_logarithmic_functions",
            name="指数函数与对数函数",
            grade="高中必修第一册",
            chapter="指数函数与对数函数",
            section="指数函数、对数函数",
            human="指数函数描述按倍数增长，对数函数是在反过来问需要多少次增长。",
            why="复利、细菌增长、声音强度和复杂度都常用这两类函数。",
            terms={
                "底数": "每次按多少倍变化的基础数。",
                "指数": "变化重复了多少次。",
                "对数": "为了得到结果，需要几个指数。",
            },
            prerequisites=["power_functions"],
            next_topics=["derivative_intro"],
            formulas=["y = a^x", "y = log_a x"],
        ),
        _point(
            topic_id="angle_radian_system",
            name="任意角与弧度制",
            grade="高中必修第一册",
            chapter="三角函数",
            section="任意角和弧度制",
            human="弧度制用半径来量角，让角和圆弧长度直接联系起来。",
            why="三角函数图像和周期变化都要用弧度更自然地描述。",
            terms={
                "弧": "圆上的一段曲线。",
                "半径": "圆心到圆上一点的距离。",
                "弧度": "用弧长和半径的比来表示角。",
            },
            prerequisites=["circle"],
            next_topics=["trigonometric_functions"],
            formulas=["theta = l / r"],
        ),
        _point(
            topic_id="trigonometric_functions",
            name="三角函数",
            grade="高中必修第一册",
            chapter="三角函数",
            section="正弦函数、余弦函数、正切函数",
            human="三角函数用角来描述圆周运动或直角三角形里的边长比例。",
            why="周期变化、波动、旋转和向量投影都离不开三角函数。",
            terms={
                "正弦": "角对应的竖直方向比例。",
                "余弦": "角对应的水平方向比例。",
                "周期": "变化重复一轮所需要的长度。",
            },
            prerequisites=["angle_radian_system", "trigonometric_ratios"],
            next_topics=["plane_vectors"],
            formulas=["sin x", "cos x", "tan x"],
        ),
        _point(
            topic_id="plane_vectors",
            name="平面向量",
            grade="高中必修第二册",
            chapter="平面向量及其应用",
            section="平面向量",
            human="向量同时说明大小和方向，不只是一个数。",
            why="力、位移、解析几何和空间几何都需要表达方向。",
            terms={
                "向量": "有大小也有方向的量。",
                "模": "向量的长度。",
                "坐标": "用数表示位置或方向。",
            },
            prerequisites=["coordinate_plane", "trigonometric_functions"],
            next_topics=["solid_geometry_spatial_relations"],
            formulas=["a + b", "lambda a"],
        ),
        _point(
            topic_id="complex_numbers",
            name="复数",
            grade="高中必修第二册",
            chapter="复数",
            section="复数的概念",
            human="复数把普通数扩展成“实部加虚部”的数，用来处理平方后为负的情况。",
            why="它让一些原本无解的方程有解，也连接平面上的点和向量。",
            terms={
                "实部": "复数里普通数轴方向的部分。",
                "虚部": "带有i的部分。",
                "i": "平方等于-1的规定符号。",
            },
            prerequisites=["quadratic_equation"],
            next_topics=["plane_vectors"],
            formulas=["z = a + bi"],
        ),
        _point(
            topic_id="solid_geometry_spatial_relations",
            name="立体几何空间关系",
            grade="高中必修第二册",
            chapter="立体几何初步",
            section="空间点、直线、平面之间的位置关系",
            human="立体几何先研究点、线、面在空间里相交、平行或垂直的关系。",
            why="空间想象和证明都要先把位置关系说准确。",
            terms={
                "平面": "无限延展的平直面。",
                "平行": "方向一致且不相交。",
                "垂直": "相交成直角。",
            },
            prerequisites=["geometric_figures_intro", "parallel_lines"],
            next_topics=["space_vectors"],
        ),
        _point(
            topic_id="solid_geometry_volume",
            name="空间几何体体积",
            grade="高中必修第二册",
            chapter="立体几何初步",
            section="空间几何体的表面积与体积",
            human="体积是在问立体内部能装多少个单位小方块。",
            why="圆柱、圆锥、棱锥和球的计算都需要统一到单位体积。",
            terms={
                "表面积": "立体外壳各面的面积总和。",
                "体积": "立体内部占据的空间大小。",
                "截面": "用平面切开立体后看到的图形。",
            },
            prerequisites=["volume"],
            next_topics=["solid_geometry_spatial_relations"],
        ),
        _point(
            topic_id="statistics_sampling",
            name="统计抽样",
            grade="高中必修第二册",
            chapter="统计",
            section="随机抽样",
            human="抽样是在无法调查全部对象时，选一部分来估计整体。",
            why="数据分析要避免只看少数特殊样本就乱下结论。",
            terms={
                "总体": "所有要研究的对象。",
                "样本": "从总体中选出来的一部分。",
                "随机": "每个对象按规则有机会被选中。",
            },
            prerequisites=["data_collection_chart"],
            next_topics=["statistical_charts_high_school"],
        ),
        _point(
            topic_id="statistical_charts_high_school",
            name="高中统计图表",
            grade="高中必修第二册",
            chapter="统计",
            section="用样本估计总体",
            human="统计图表把数据整理成能看出分布、集中程度和波动的形式。",
            why="看图读数据是概率统计和现实决策的基础。",
            terms={
                "分布": "数据落在不同范围的情况。",
                "频率": "某类结果出现的比例。",
                "波动": "数据离集中位置有多分散。",
            },
            prerequisites=["statistics_sampling"],
            next_topics=["normal_distribution"],
        ),
        _point(
            topic_id="probability_high_school",
            name="高中概率",
            grade="高中必修第二册",
            chapter="概率",
            section="随机事件与概率",
            human="概率是在描述随机事件发生的可能性大小。",
            why="选择模型、判断风险和理解统计结论都需要概率。",
            terms={
                "随机事件": "可能发生也可能不发生的事情。",
                "样本空间": "所有可能结果的集合。",
                "概率": "可能性大小的数值表示。",
            },
            prerequisites=["probability"],
            next_topics=["counting_principle", "conditional_probability"],
        ),
        _point(
            topic_id="space_vectors",
            name="空间向量",
            grade="高中选择性必修第一册",
            chapter="空间向量与立体几何",
            section="空间向量及其运算",
            human="空间向量用三个方向的数描述空间里的大小和方向。",
            why="它能把立体几何里的位置关系转成可计算的问题。",
            terms={
                "空间": "有长、宽、高三个方向的环境。",
                "坐标": "用数确定位置。",
                "数量积": "用来判断夹角和垂直的运算。",
            },
            prerequisites=["plane_vectors", "solid_geometry_spatial_relations"],
            next_topics=["line_plane_equations"],
        ),
        _point(
            topic_id="line_plane_equations",
            name="直线和平面方程",
            grade="高中选择性必修第一册",
            chapter="空间向量与立体几何",
            section="直线和平面的方程",
            human="直线和平面方程是用等式描述空间中点的位置限制。",
            why="解析几何要把图形关系转成代数关系。",
            terms={
                "方程": "限制点必须满足的等式。",
                "法向量": "垂直于平面的向量。",
                "方向向量": "说明直线方向的向量。",
            },
            prerequisites=["space_vectors"],
            next_topics=["conic_sections"],
        ),
        _point(
            topic_id="conic_sections",
            name="圆锥曲线",
            grade="高中选择性必修第一册",
            chapter="圆锥曲线的方程",
            section="椭圆、双曲线、抛物线",
            human="圆锥曲线是由距离关系定义出来的一类平面曲线。",
            why="它把几何形状、方程和运动轨迹联系在一起。",
            terms={
                "焦点": "决定曲线形状的特殊点。",
                "轨迹": "点按规则运动留下的图形。",
                "离心率": "描述曲线开合程度的数。",
            },
            prerequisites=["line_plane_equations", "quadratic_function_high_school"],
            next_topics=["derivative_applications"],
        ),
        _point(
            topic_id="sequence_arithmetic",
            name="等差数列",
            grade="高中选择性必修第二册",
            chapter="数列",
            section="等差数列",
            human="等差数列是相邻两项每次增加同一个数的数列。",
            why="它描述稳定增加或减少的离散变化。",
            terms={
                "数列": "按顺序排成的一串数。",
                "项": "数列里的每一个数。",
                "公差": "相邻两项的固定差。",
            },
            prerequisites=["arithmetic_operations"],
            next_topics=["sequence_geometric"],
            formulas=["a_n = a_1 + (n - 1)d"],
        ),
        _point(
            topic_id="sequence_geometric",
            name="等比数列",
            grade="高中选择性必修第二册",
            chapter="数列",
            section="等比数列",
            human="等比数列是相邻两项每次乘同一个数的数列。",
            why="它描述按倍数增长或衰减的离散变化。",
            terms={
                "公比": "相邻两项的固定倍数。",
                "项数": "第几个数。",
                "前n项和": "前面n个数加起来。",
            },
            prerequisites=["sequence_arithmetic", "exponential_logarithmic_functions"],
            next_topics=["derivative_intro"],
            formulas=["a_n = a_1 q^(n-1)"],
        ),
        _point(
            topic_id="sequence_summation",
            name="数列求和",
            grade="高中选择性必修第二册",
            chapter="数列",
            section="数列求和",
            human="数列求和是在把一串按规则排列的数加起来，并寻找不逐项相加的办法。",
            why="很多离散增长问题、分期付款和递推问题都要计算一段数列的总量。",
            terms={
                "求和": "把若干项加起来。",
                "通项": "表示第n项的式子。",
                "前n项和": "从第1项加到第n项的总和。",
            },
            prerequisites=["sequence_arithmetic", "sequence_geometric"],
            next_topics=["derivative_intro"],
            formulas=["S_n = a_1 + a_2 + ... + a_n"],
        ),
        _point(
            topic_id="derivative_intro",
            name="导数入门",
            grade="高中选择性必修第二册",
            chapter="导数及其应用",
            section="导数的概念",
            human="导数是在问函数某一点附近变化得有多快。",
            why="研究速度、切线斜率、函数增减和最值都要用导数。",
            terms={
                "变化率": "输出变化量和输入变化量的比。",
                "切线": "在某一点贴着曲线的直线。",
                "极限": "无限接近某个值的过程。",
            },
            prerequisites=["function_properties_high_school"],
            next_topics=["derivative_applications"],
            formulas=["f'(x)"],
        ),
        _point(
            topic_id="derivative_applications",
            name="导数应用",
            grade="高中选择性必修第二册",
            chapter="导数及其应用",
            section="利用导数研究函数",
            human="导数应用是用变化快慢判断函数增减、最值和图像形状。",
            why="很多复杂函数不能靠直观看图，导数给出可计算的判断方法。",
            terms={
                "单调": "函数整体上变大或变小。",
                "极值": "附近范围内的最大或最小。",
                "最值": "整个范围内最大或最小。",
            },
            prerequisites=["derivative_intro"],
            next_topics=["normal_distribution"],
        ),
        _point(
            topic_id="counting_principle",
            name="计数原理",
            grade="高中选择性必修第三册",
            chapter="计数原理",
            section="分类加法计数原理与分步乘法计数原理",
            human="计数原理是在有很多可能时，有顺序、不重复、不遗漏地数出来。",
            why="排列组合和概率计算都先依赖正确计数。",
            terms={
                "分类": "几种互不重叠的选择。",
                "分步": "完成一件事需要连续几个步骤。",
                "不重不漏": "不重复计算，也不漏掉情况。",
            },
            prerequisites=["probability_high_school"],
            next_topics=["permutation_combination"],
        ),
        _point(
            topic_id="permutation_combination",
            name="排列与组合",
            grade="高中选择性必修第三册",
            chapter="计数原理",
            section="排列与组合",
            human="排列关心顺序，组合只关心选了哪些对象。",
            why="概率题里很多错误来自没有分清顺序是否重要。",
            terms={
                "排列": "选出来还要排顺序。",
                "组合": "只选对象不排顺序。",
                "阶乘": "从一个正整数一直乘到1。",
            },
            prerequisites=["counting_principle"],
            next_topics=["binomial_theorem"],
            formulas=["A(n,m)", "C(n,m)"],
        ),
        _point(
            topic_id="binomial_theorem",
            name="二项式定理",
            grade="高中选择性必修第三册",
            chapter="计数原理",
            section="二项式定理",
            human="二项式定理是在展开两个项的和的高次方时，快速找到每一项。",
            why="它连接展开式、组合数和概率分布。",
            terms={
                "二项式": "由两个项相加或相减组成的式子。",
                "展开": "把乘方写成多项相加。",
                "系数": "项前面乘着的数。",
            },
            prerequisites=["permutation_combination", "polynomial_multiplication"],
            next_topics=["normal_distribution"],
            formulas=["(a + b)^n"],
        ),
        _point(
            topic_id="conditional_probability",
            name="条件概率",
            grade="高中选择性必修第三册",
            chapter="概率",
            section="条件概率与全概率公式",
            human="条件概率是在已知某件事发生后，重新判断另一件事的可能性。",
            why="现实判断常常有已知条件，不能还按原来的总体直接算。",
            terms={
                "条件": "已经知道成立的信息。",
                "事件": "要讨论的结果集合。",
                "更新": "根据新信息重新计算。",
            },
            prerequisites=["probability_high_school"],
            next_topics=["normal_distribution"],
            formulas=["P(A|B)"],
        ),
        _point(
            topic_id="random_variables",
            name="随机变量",
            grade="高中选择性必修第三册",
            chapter="随机变量及其分布",
            section="离散型随机变量及其分布列",
            human="随机变量是把随机结果用数表示，方便计算和比较。",
            why="要研究平均结果和波动程度，先要把随机现象数值化。",
            terms={
                "随机": "结果事先不确定。",
                "变量": "可能取不同值的量。",
                "分布": "每个可能值出现的概率安排。",
            },
            prerequisites=["conditional_probability"],
            next_topics=["normal_distribution"],
        ),
        _point(
            topic_id="normal_distribution",
            name="正态分布",
            grade="高中选择性必修第三册",
            chapter="随机变量及其分布",
            section="正态分布",
            human="正态分布描述很多数据集中在平均值附近、越远越少的形状。",
            why="身高、测量误差和抽样估计经常用正态分布近似。",
            terms={
                "平均值": "数据中心位置。",
                "标准差": "数据离中心有多分散。",
                "密度曲线": "用曲线表示概率集中在哪里。",
            },
            prerequisites=["random_variables", "statistical_charts_high_school"],
        ),
    ]
